In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_excel("Titanic.xlsx",sheet_name="Titanic")

In [3]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df.set_index?

In [4]:
df.set_index("PassengerId")

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
df.set_index("PassengerId",inplace = True)

In [6]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [7]:
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [8]:
df.head(10)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [9]:
df.tail()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [10]:
df.tail(10)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
883,0,3,"Dahlberg, Miss Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [11]:
df.sample()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
128,1,3,"Madsen, Mr. Fridtjof Arne",male,24.0,0,0,C 17369,7.1417,NaN,S

In [12]:
df.sample(10)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
285,0,1,"Smith, Mr. Richard William",male,NaN,0,0,113056,26.0000,A19,S
333,0,1,"Graham, Mr. George Edward",male,38.0,0,1,PC 17582,153.4625,C91,S
597,1,2,"Leitch, Miss Jessie Wills",female,NaN,0,0,248727,33.0000,NaN,S
512,0,3,"Webber, Mr. James",male,NaN,0,0,SOTON/OQ 3101316,8.0500,NaN,S
837,0,3,"Pasic, Mr. Jakob",male,21.0,0,0,315097,8.6625,NaN,S
550,1,2,"Davies, Master John Morgan Jr",male,8.0,1,1,C.A. 33112,36.7500,NaN,S
75,1,3,"Bing, Mr. Lee",male,32.0,0,0,1601,56.4958,NaN,S
665,1,3,"Lindqvist, Mr. Eino William",male,20.0,1,0,STON/O 2. 3101285,7.9250,NaN,S
383,0,3,"Tikkanen, Mr. Juho",male,32.0,0,0,STON/O 2. 3101293,7.9250,NaN,S
488,0,1,"Kent, Mr. Edward Austin",male,58.0,0,0,11771,29.7000,B37,C

In [13]:
clos =df.columns

In [14]:
clos

Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket',
       'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [15]:
rows = df.index

In [16]:
rows

RangeIndex(start=1, stop=892, step=1, name='PassengerId')

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 1 to 891
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Name      891 non-null    str
 3   Sex       891 non-null    str
 4   Age       714 non-null    float64
 5   SibSp     891 non-null    int64
 6   Parch     891 non-null    int64
 7   Ticket    891 non-null    str
 8   Fare      891 non-null    float64
 9   Cabin     204 non-null    str
 10  Embarked  889 non-null    str
dtypes: float64(2), int64(4), str(5)
memory usage: 111.7 KB

In [18]:
df.shape

(891, 11)

In [19]:
rows_count = df.shape[0]

In [20]:
rows_count

891

In [21]:
columns_count = df.shape[1]

In [22]:
columns_count

11

In [23]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [24]:
df.describe()

         Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [25]:
df['Age']

PassengerId
1      22.0
2      38.0
3      26.0
4      35.0
5      35.0
       ...
887    27.0
888    19.0
889     NaN
890    26.0
891    32.0
Name: Age, Length: 891, dtype: float64

In [26]:
df[["Age"]]

              Age
PassengerId
1            22.0
2            38.0
3            26.0
4            35.0
5            35.0
...           ...
887          27.0
888          19.0
889           NaN
890          26.0
891          32.0

[891 rows x 1 columns]

In [27]:
df[["Age","Pclass"]]

              Age  Pclass
PassengerId
1            22.0       3
2            38.0       1
3            26.0       3
4            35.0       1
5            35.0       3
...           ...     ...
887          27.0       2
888          19.0       1
889           NaN       3
890          26.0       1
891          32.0       3

[891 rows x 2 columns]

In [28]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [29]:
df.loc[6,:]

Survived                   0
Pclass                     3
Name        Moran, Mr. James
Sex                     male
Age                      NaN
SibSp                      0
Parch                      0
Ticket                330877
Fare                  8.4583
Cabin                    NaN
Embarked                   Q
Name: 6, dtype: object

In [30]:
df.loc[6,"Age"]

np.float64(nan)

In [31]:
df.loc[5:10,"Age":]

              Age  SibSp  Parch  Ticket     Fare Cabin Embarked
PassengerId
5            35.0      0      0  373450   8.0500   NaN        S
6             NaN      0      0  330877   8.4583   NaN        Q
7            54.0      0      0   17463  51.8625   E46        S
8             2.0      3      1  349909  21.0750   NaN        S
9            27.0      0      2  347742  11.1333   NaN        S
10           14.0      1      0  237736  30.0708   NaN        C

In [32]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [33]:
df.iloc[5:10,4:]

              Age  SibSp  Parch  Ticket     Fare Cabin Embarked
PassengerId
6             NaN      0      0  330877   8.4583   NaN        Q
7            54.0      0      0   17463  51.8625   E46        S
8             2.0      3      1  349909  21.0750   NaN        S
9            27.0      0      2  347742  11.1333   NaN        S
10           14.0      1      0  237736  30.0708   NaN        C

In [34]:
df.iloc[6,4]

np.float64(54.0)

In [35]:
df.iloc[[5,9,8,4,10],:]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
11,1,3,"Sandstrom, Miss Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S

In [ ]:
df.info()

In [36]:
df.nunique()

Survived      2
Pclass        3
Name        891
Sex           2
Age          88
SibSp         7
Parch         7
Ticket      681
Fare        248
Cabin       147
Embarked      3
dtype: int64

In [37]:
df["Survived"].nunique()

2

In [38]:
df["Survived"].unique()

array([0, 1])

In [39]:
df["Embarked"].unique()

<ArrowStringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

In [40]:
df.isnull()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,False,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...
887,False,False,False,False,False,False,False,False,False,True,False
888,False,False,False,False,False,False,False,False,False,False,False
889,False,False,False,False,True,False,False,False,False,True,False
890,False,False,False,False,False,False,False,False,False,False,False
891,False,False,False,False,False,False,False,False,False,True,False

In [41]:
df.isnull().sum()

Survived      0
Pclass        0
Name          0
Sex           0
Age         177
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [42]:
df.isnull().mean()*100

Survived     0.000000
Pclass       0.000000
Name         0.000000
Sex          0.000000
Age         19.865320
SibSp        0.000000
Parch        0.000000
Ticket       0.000000
Fare         0.000000
Cabin       77.104377
Embarked     0.224467
dtype: float64

In [43]:
df["Age"]>70

PassengerId
1      False
2      False
3      False
4      False
5      False
       ...
887    False
888    False
889    False
890    False
891    False
Name: Age, Length: 891, dtype: bool

In [44]:
(df["Age"]>70).sum()

np.int64(5)

In [45]:
df[df["Age"]>70] # boolean filtering

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [46]:
df[(df["Age"]>70) | (df["Age"]<10)]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
8,0,3,"Palsson, Master Gosta Leonard",male,2.00,3,1,349909,21.0750,NaN,S
11,1,3,"Sandstrom, Miss Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S
17,0,3,"Rice, Master Eugene",male,2.00,4,1,382652,29.1250,NaN,Q
25,0,3,"Palsson, Miss Torborg Danira",female,8.00,3,1,349909,21.0750,NaN,S
44,1,2,"Laroche, Miss Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...
832,1,2,"Richards, Master George Sibley",male,0.83,1,1,29106,18.7500,NaN,S
851,0,3,"Andersson, Master Sigvard Harald Elias",male,4.00,4,2,347082,31.2750,NaN,S
852,0,3,"Svensson, Mr. Johan",male,74.00,0,0,347060,7.7750,NaN,S
853,0,3,"Boulos, Miss Nourelain",female,9.00,1,1,2678,15.2458,NaN,C
870,1,3,"Johnson, Master Harold Theodor",male,4.00,1,1,347742,11.1333,NaN,S

In [ ]:
df

In [47]:
df["ASD"] = 1+2

In [48]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ASD
PassengerId,,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,3
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,3
3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,3
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,3
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,3
...,...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,3
888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,3
889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,3
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,3
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,3

In [ ]:
df.insert?

In [49]:
df.insert(2,"Dfgg",0)

In [50]:
df

,Survived,Pclass,Dfgg,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ASD
PassengerId,,,,,,,,,,,,,
1,0,3,0,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,3
2,1,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,3
3,1,3,0,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,3
4,1,1,0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,3
5,0,3,0,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,0,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,3
888,1,1,0,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,3
889,0,3,0,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,3
890,1,1,0,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,3
891,0,3,0,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,3

In [ ]:
df.sort_values?

In [51]:
df.sort_values(by="Age")

,Survived,Pclass,Dfgg,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ASD
PassengerId,,,,,,,,,,,,,
804,1,3,0,"Thomas, Master Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C,3
756,1,2,0,"Hamalainen, Master Viljo",male,0.67,1,1,250649,14.5000,NaN,S,3
645,1,3,0,"Baclini, Miss Eugenie",female,0.75,2,1,2666,19.2583,NaN,C,3
470,1,3,0,"Baclini, Miss Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C,3
79,1,2,0,"Caldwell, Master Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
860,0,3,0,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C,3
864,0,3,0,"Sage, Miss Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S,3
869,0,3,0,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S,3
879,0,3,0,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S,3
889,0,3,0,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,3

In [ ]:
df.sort_index?

In [52]:
df.sort_values(by="Age",ascending=False)

,Survived,Pclass,Dfgg,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ASD
PassengerId,,,,,,,,,,,,,
631,1,1,0,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S,3
852,0,3,0,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S,3
494,0,1,0,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C,3
97,0,1,0,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C,3
117,0,3,0,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
860,0,3,0,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C,3
864,0,3,0,"Sage, Miss Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S,3
869,0,3,0,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S,3
879,0,3,0,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S,3
889,0,3,0,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,3

In [53]:
df.sort_values(by=["Sex","Age"],ascending=[True,False])

,Survived,Pclass,Dfgg,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ASD
PassengerId,,,,,,,,,,,,,
276,1,1,0,"Andrews, Miss Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,3
484,1,3,0,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S,3
830,1,1,0,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN,3
367,1,1,0,"Warren, Mrs. Frank Manley (Anna Sophia Atkinson)",female,60.0,1,0,110813,75.2500,D37,C,3
12,1,1,0,"Bonnell, Miss Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
840,1,1,0,"Marechal, Mr. Pierre",male,NaN,0,0,11774,29.7000,C47,C,3
847,0,3,0,"Sage, Mr. Douglas Bullen",male,NaN,8,2,CA. 2343,69.5500,NaN,S,3
860,0,3,0,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C,3
869,0,3,0,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S,3
879,0,3,0,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S,3

In [54]:
df.sort_index(ascending= False)

,Survived,Pclass,Dfgg,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ASD
PassengerId,,,,,,,,,,,,,
891,0,3,0,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,3
890,1,1,0,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,3
889,0,3,0,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,3
888,1,1,0,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,3
887,0,2,0,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5,0,3,0,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,3
4,1,1,0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,3
3,1,3,0,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,3
2,1,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,3
1,0,3,0,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,3

In [55]:
df.sort_index(axis = 1,ascending= False)

,Ticket,Survived,SibSp,Sex,Pclass,Parch,Name,Fare,Embarked,Dfgg,Cabin,Age,ASD
PassengerId,,,,,,,,,,,,,
1,A/5 21171,0,1,male,3,0,"Braund, Mr. Owen Harris",7.2500,S,0,NaN,22.0,3
2,PC 17599,1,1,female,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",71.2833,C,0,C85,38.0,3
3,STON/O2. 3101282,1,0,female,3,0,"Heikkinen, Miss Laina",7.9250,S,0,NaN,26.0,3
4,113803,1,1,female,1,0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",53.1000,S,0,C123,35.0,3
5,373450,0,0,male,3,0,"Allen, Mr. William Henry",8.0500,S,0,NaN,35.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,211536,0,0,male,2,0,"Montvila, Rev. Juozas",13.0000,S,0,NaN,27.0,3
888,112053,1,0,female,1,0,"Graham, Miss Margaret Edith",30.0000,S,0,B42,19.0,3
889,W./C. 6607,0,1,female,3,2,"Johnston, Miss Catherine Helen ""Carrie""",23.4500,S,0,NaN,NaN,3
890,111369,1,0,male,1,0,"Behr, Mr. Karl Howell",30.0000,C,0,C148,26.0,3
891,370376,0,0,male,3,0,"Dooley, Mr. Patrick",7.7500,Q,0,NaN,32.0,3

In [ ]:
# axis=1 refers to columns
df.sort_index(axis=1,ascending=False)

In [56]:
# Select only passengers older than 30
adults = df[df['Age'] > 30]

In [57]:
adults

,Survived,Pclass,Dfgg,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ASD
PassengerId,,,,,,,,,,,,,
2,1,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,3
4,1,1,0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,3
5,0,3,0,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,3
7,0,1,0,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,3
12,1,1,0,"Bonnell, Miss Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
874,0,3,0,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S,3
880,1,1,0,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,3
882,0,3,0,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S,3
886,0,3,0,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q,3
891,0,3,0,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,3

In [58]:
# Select females AND passengers in 1st class
rich_females = df[(df['Sex'] == 'female') & (df['Pclass'] == 1)]

# Select passengers who paid more than $100 OR are in 1st class
high_value = df[(df['Fare'] > 100) | (df['Pclass'] == 1)]

In [59]:
rich_females

,Survived,Pclass,Dfgg,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ASD
PassengerId,,,,,,,,,,,,,
2,1,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,3
4,1,1,0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,3
12,1,1,0,"Bonnell, Miss Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,3
32,1,1,0,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C,3
53,1,1,0,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
857,1,1,0,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S,3
863,1,1,0,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S,3
872,1,1,0,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,3
880,1,1,0,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,3
888,1,1,0,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,3

In [60]:
# Select passengers embarking from Southampton (S) or Cherbourg (C)
ports = df[df['Embarked'].isin(['S', 'C'])]

In [61]:
ports

,Survived,Pclass,Dfgg,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ASD
PassengerId,,,,,,,,,,,,,
1,0,3,0,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,3
2,1,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,3
3,1,3,0,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,3
4,1,1,0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,3
5,0,3,0,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,0,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S,3
887,0,2,0,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,3
888,1,1,0,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,3
889,0,3,0,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,3
890,1,1,0,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,3

In [62]:
# Select anyone with "Mr." in their name
misters = df[df['Name'].str.contains("Mr.",regex = False)]

# Select names that start with "A"
starts_with_a = df[df['Name'].str.startswith("A")]

In [63]:
misters

,Survived,Pclass,Dfgg,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ASD
PassengerId,,,,,,,,,,,,,
1,0,3,0,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,3
5,0,3,0,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,3
6,0,3,0,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,3
7,0,1,0,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,3
13,0,3,0,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,0,3,0,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S,3
884,0,2,0,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S,3
885,0,3,0,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S,3
890,1,1,0,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,3
891,0,3,0,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,3

In [64]:
starts_with_a

,Survived,Pclass,Dfgg,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ASD
PassengerId,,,,,,,,,,,,,
5,0,3,0,"Allen, Mr. William Henry",male,35.00,0,0,373450,8.0500,NaN,S,3
14,0,3,0,"Andersson, Mr. Anders Johan",male,39.00,1,5,347082,31.2750,NaN,S,3
26,1,3,0,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.00,1,5,347077,31.3875,NaN,S,3
41,0,3,0,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.00,1,0,7546,9.4750,NaN,S,3
50,0,3,0,"Arnold-Franchi, Mrs. Josef (Josefine Franchi)",female,18.00,1,0,349237,17.8000,NaN,S,3
69,1,3,0,"Andersson, Miss Erna Alexandra",female,17.00,4,2,3101281,7.9250,NaN,S,3
92,0,3,0,"Andreasson, Mr. Paul Edvin",male,20.00,0,0,347466,7.8542,NaN,S,3
115,0,3,0,"Attalah, Miss Malake",female,17.00,0,0,2627,14.4583,NaN,C,3
120,0,3,0,"Andersson, Miss Ellis Anna Maria",female,2.00,4,2,347082,31.2750,NaN,S,3
145,0,2,0,"Andrew, Mr. Edgardo Samuel",male,18.00,0,0,231945,11.5000,NaN,S,3
147,1,3,0,"Andersson, Mr. August Edvard (""Wennerstrom"")",male,27.00,0,0,350043,7.7958,NaN,S,3
183,0,3,0,"Asplund, Master Clarence Gustaf Hugo",male,9.00,4,2,347077,31.3875,NaN,S,3
193,1,3,0,"Andersen-Jensen, Miss Carla Christine Nielsine",female,19.00,1,0,350046,7.8542,NaN,S,3
208,1,3,0,"Albimona, Mr. Nassef Cassem",male,26.00,0,0,2699,18.7875,NaN,C,3
211,0,3,0,"Ali, Mr. Ahmed",male,24.00,0,0,SOTON/O.Q. 3101311,7.0500,NaN,S,3
234,1,3,0,"Asplund, Miss Lillian Gertrud",female,5.00,4,2,347077,31.3875,NaN,S,3
245,0,3,0,"Attalah, Mr. Sleiman",male,30.00,0,0,2694,7.2250,NaN,C,3
262,1,3,0,"Asplund, Master Edvin Rojj Felix",male,3.00,4,2,347077,31.3875,NaN,S,3
276,1,1,0,"Andrews, Miss Kornelia Theodosia",female,63.00,1,0,13502,77.9583,D7,S,3
280,1,3,0,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35.00,1,1,C.A. 2673,20.2500,NaN,S,3
298,0,1,0,"Allison, Miss Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,3
306,1,1,0,"Allison, Master Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,3
309,0,2,0,"Abelson, Mr. Samuel",male,30.00,1,0,P/PP 3381,24.0000,NaN,C,3
354,0,3,0,"Arnold-Franchi, Mr. Josef",male,25.00,1,0,349237,17.8000,NaN,S,3
364,0,3,0,"Asim, Mr. Adola",male,35.00,0,0,SOTON/O.Q. 3101310,7.0500,NaN,S,3
366,0,3,0,"Adahl, Mr. Mauritz Nils Martin",male,30.00,0,0,C 7076,7.2500,NaN,S,3
370,1,1,0,"Aubart, Mme. Leontine Pauline",female,24.00,0,0,PC 17477,69.3000,B35,C,3
402,0,3,0,"Adams, Mr. John",male,26.00,0,0,341826,8.0500,NaN,S,3
461,1,1,0,"Anderson, Mr. Harry",male,48.00,0,0,19952,26.5500,E12,S,3
494,0,1,0,"Artagaveytia, Mr. Ramon",male,71.00,0,0,PC 17609,49.5042,NaN,C,3
499,0,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,3
519,1,2,0,"Angle, Mrs. William A (Florence ""Mary"" Agnes H...",female,36.00,1,0,226875,26.0000,NaN,S,3
542,0,3,0,"Andersson, Miss Ingeborg Constanzia",female,9.00,4,2,347082,31.2750,NaN,S,3
543,0,3,0,"Andersson, Miss Sigrid Elisabeth",female,11.00,4,2,347082,31.2750,NaN,S,3
572,1,1,0,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.00,2,0,11769,51.4792,C101,S,3
611,0,3,0,"Andersson, Mrs. Anders Johan (Alfrida Konstant...",female,39.00,1,5,347082,31.2750,NaN,S,3
701,1,1,0,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.00,1,0,PC 17757,227.5250,C62 C64,C,3
731,1,1,0,"Allen, Miss Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,3
747,0,3,0,"Abbott, Mr. Rossmore Edward",male,16.00,1,1,C.A. 2673,20.2500,NaN,S,3
781,1,3,0,"Ayoub, Miss Banoura",female,13.00,0,0,2687,7.2292,NaN,C,3
785,0,3,0,"Ali, Mr. William",male,25.00,0,0,SOTON/O.Q. 3101312,7.0500,NaN,S,3
807,0,1,0,"Andrews, Mr. Thomas Jr",male,39.00,0,0,112050,0.0000,A36,S,3
811,0,3,0,"Alexander, Mr. William",male,26.00,0,0,3474,7.8875,NaN,S,3
814,0,3,0,"Andersson, Miss Ebba Iris Alfrida",female,6.00,4,2,347082,31.2750,NaN,S,3
834,0,3,0,"Augustsson, Mr. Albert",male,23.00,0,0,347468,7.8542,NaN,S,3
835,0,3,0,"Allum, Mr. Owen George",male,18.00,0,0,2223,8.3000,NaN,S,3
841,0,3,0,"Alhomaki, Mr. Ilmari Rudolf",male,20.00,0,0,SOTON/O2 3101287,7.9250,NaN,S,3
846,0,3,0,"Abbing, Mr. Anthony",male,42.00,0,0,C.A. 5547,7.5500,NaN,S,3
851,0,3,0,"Andersson, Master Sigvard Harald Elias",male,4.00,4,2,347082,31.2750,NaN,S,3
856,1,3,0,"Aks, Mrs. Sam (Leah Rosen)",female,18.00,0,1,392091,9.3500,NaN,S,3
875,1,2,0,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.00,1,0,P/PP 3381,24.0000,NaN,C,3

In [65]:
df["Sex"].str.title()

PassengerId
1        Male
2      Female
3      Female
4      Female
5        Male
        ...
887      Male
888    Female
889    Female
890      Male
891      Male
Name: Sex, Length: 891, dtype: str

In [66]:
# Same as Method 2, but cleaner to read
rich_females = df.query('Sex == "female" and Pclass == 1')

In [67]:
rich_females

,Survived,Pclass,Dfgg,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ASD
PassengerId,,,,,,,,,,,,,
2,1,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,3
4,1,1,0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,3
12,1,1,0,"Bonnell, Miss Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,3
32,1,1,0,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C,3
53,1,1,0,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
857,1,1,0,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S,3
863,1,1,0,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S,3
872,1,1,0,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,3
880,1,1,0,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,3
888,1,1,0,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,3

In [68]:
rich_females[rich_females["Name"].str.contains("Mrs.",regex = False)]["Survived"].value_counts()

Survived
1    41
0     1
Name: count, dtype: int64

In [69]:
# Shows the count of missing values per column
df.isnull().sum()

Survived      0
Pclass        0
Dfgg          0
Name          0
Sex           0
Age         177
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       687
Embarked      2
ASD           0
dtype: int64

In [70]:
# Returns True if the column contains any nulls
df.isnull().any()

Survived    False
Pclass      False
Dfgg        False
Name        False
Sex         False
Age          True
SibSp       False
Parch       False
Ticket      False
Fare        False
Cabin        True
Embarked     True
ASD         False
dtype: bool

In [71]:
# Counts how many rows are duplicates
df[df.duplicated()]

Empty DataFrame
Columns: [Survived, Pclass, Dfgg, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked, ASD]
Index: []

In [72]:
# Counts how many rows are duplicates
df.duplicated().sum()

np.int64(0)

In [73]:
df.duplicated(subset = ["Sex","Pclass","Embarked"],keep = False)

PassengerId
1      True
2      True
3      True
4      True
5      True
       ...
887    True
888    True
889    True
890    True
891    True
Length: 891, dtype: bool

In [74]:
df[df["Embarked"] == "Q"]

,Survived,Pclass,Dfgg,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ASD
PassengerId,,,,,,,,,,,,,
6,0,3,0,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,3
17,0,3,0,"Rice, Master Eugene",male,2.0,4,1,382652,29.1250,NaN,Q,3
23,1,3,0,"McGowan, Miss Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q,3
29,1,3,0,"O'Dwyer, Miss Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q,3
33,1,3,0,"Glynn, Miss Mary Agatha",female,NaN,0,0,335677,7.7500,NaN,Q,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
791,0,3,0,"Keane, Mr. Andrew ""Andy""",male,NaN,0,0,12460,7.7500,NaN,Q,3
826,0,3,0,"Flynn, Mr. John",male,NaN,0,0,368323,6.9500,NaN,Q,3
829,1,3,0,"McCormack, Mr. Thomas Joseph",male,NaN,0,0,367228,7.7500,NaN,Q,3
886,0,3,0,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q,3
891,0,3,0,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,3

In [75]:
df.query('Sex == "male" and Pclass == 1 and Embarked == "Q"')

,Survived,Pclass,Dfgg,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ASD
PassengerId,,,,,,,,,,,,,
246,0,1,0,"Minahan, Dr. William Edward",male,44.0,2,0,19928,90.0,C78,Q,3

In [76]:
df.query('Sex == "female" and Pclass == 1 and Embarked == "Q"')

,Survived,Pclass,Dfgg,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ASD
PassengerId,,,,,,,,,,,,,
413,1,1,0,"Minahan, Miss Daisy E",female,33.0,1,0,19928,90.0,C78,Q,3

In [77]:
df.query('Sex == "male" and Pclass == 2 and Embarked == "Q"')

,Survived,Pclass,Dfgg,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ASD
PassengerId,,,,,,,,,,,,,
627,0,2,0,"Kirkland, Rev. Charles Leonard",male,57.0,0,0,219533,12.35,NaN,Q,3

In [78]:
df[~df.duplicated(subset = ["Sex","Pclass","Embarked"],keep = False)]

,Survived,Pclass,Dfgg,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ASD
PassengerId,,,,,,,,,,,,,
246,0,1,0,"Minahan, Dr. William Edward",male,44.0,2,0,19928,90.00,C78,Q,3
413,1,1,0,"Minahan, Miss Daisy E",female,33.0,1,0,19928,90.00,C78,Q,3
627,0,2,0,"Kirkland, Rev. Charles Leonard",male,57.0,0,0,219533,12.35,NaN,Q,3

In [79]:
df[~df.duplicated(subset=["Pclass","Sex","Embarked"],keep = False)]

,Survived,Pclass,Dfgg,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ASD
PassengerId,,,,,,,,,,,,,
246,0,1,0,"Minahan, Dr. William Edward",male,44.0,2,0,19928,90.00,C78,Q,3
413,1,1,0,"Minahan, Miss Daisy E",female,33.0,1,0,19928,90.00,C78,Q,3
627,0,2,0,"Kirkland, Rev. Charles Leonard",male,57.0,0,0,219533,12.35,NaN,Q,3

In [80]:
df.query('Pclass == 2 and Embarked == "Q"')

,Survived,Pclass,Dfgg,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ASD
PassengerId,,,,,,,,,,,,,
304,1,2,0,"Keane, Miss Nora A",female,NaN,0,0,226593,12.35,E101,Q,3
323,1,2,0,"Slayter, Miss Hilda Mary",female,30.0,0,0,234818,12.35,NaN,Q,3
627,0,2,0,"Kirkland, Rev. Charles Leonard",male,57.0,0,0,219533,12.35,NaN,Q,3

In [81]:
df[df["Embarked"]=="Q"].groupby("Pclass")["Pclass"].count()

Pclass
1     2
2     3
3    72
Name: Pclass, dtype: int64

In [85]:
(df[df["Embarked"]=="Q"].groupby("Pclass"))["Sex"].value_counts()

Pclass  Sex
1       male       1
        female     1
2       female     2
        male       1
3       male      39
        female    33
Name: count, dtype: int64

In [ ]:
# Filters the DataFrame to show only the duplicated rows
df[df.duplicated(keep=False)]

In [ ]:
# Removes duplicate rows, keeping the first occurrence
df.drop_duplicates(subset=["Pclass","Sex","Embarked"],keep = False)

In [ ]:
# Shows the dtype of each column
df.dtypes

In [86]:
# Converts the 'PassengerId' column to string (object)
s=df['Survived'].astype('str')

In [87]:
# Converts the 'PassengerId' column to string (object)
z=df['Name'].astype('int',errors = 'ignore')

In [88]:
z

PassengerId
1                                Braund, Mr. Owen Harris
2      Cumings, Mrs. John Bradley (Florence Briggs Th...
3                                  Heikkinen, Miss Laina
4           Futrelle, Mrs. Jacques Heath (Lily May Peel)
5                               Allen, Mr. William Henry
                             ...
887                                Montvila, Rev. Juozas
888                          Graham, Miss Margaret Edith
889              Johnston, Miss Catherine Helen "Carrie"
890                                Behr, Mr. Karl Howell
891                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [ ]:
# Converts the 'PassengerId' column to string (object)
df.astype?

In [89]:
s

PassengerId
1      0
2      1
3      1
4      1
5      0
      ..
887    0
888    1
889    0
890    1
891    0
Name: Survived, Length: 891, dtype: str

In [90]:
s[1]+s[2]

'01'

In [ ]:
# Shows the count of unique values per column
df.nunique()

In [91]:
# Shows the counts for each unique value in the 'Embarked' column
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [92]:
# Shows the counts for each unique value in the 'Sex' column
df['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [93]:
df["Pclass"].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [94]:
df.dtypes

Survived      int64
Pclass        int64
Dfgg          int64
Name            str
Sex             str
Age         float64
SibSp         int64
Parch         int64
Ticket          str
Fare        float64
Cabin           str
Embarked        str
ASD           int64
dtype: object

In [95]:
df["Age_New"]=df['Age'].astype(dtype='int64',errors="ignore")

In [96]:
df

,Survived,Pclass,Dfgg,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ASD,Age_New
PassengerId,,,,,,,,,,,,,,
1,0,3,0,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,3,22.0
2,1,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,3,38.0
3,1,3,0,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,3,26.0
4,1,1,0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,3,35.0
5,0,3,0,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,3,35.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,0,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,3,27.0
888,1,1,0,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,3,19.0
889,0,3,0,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,3,NaN
890,1,1,0,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,3,26.0
891,0,3,0,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,3,32.0

In [98]:
pd.to_numeric?

Signature:
pd.to_numeric(
    arg,
    errors: 'DateTimeErrorChoices' = 'raise',
    downcast: "Literal['integer', 'signed', 'unsigned', 'float'] | None" = None,
    dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>,
)
Docstring:
Convert argument to a numeric type.

If the input is already of a numeric dtype, the dtype will be preserved.
For non-numeric inputs, the default return dtype is `float64` or `int64`
depending on the data supplied. Use the `downcast` parameter
to obtain other dtypes.

Please note that precision loss may occur if really large numbers
are passed in. Due to the internal limitations of `ndarray`, if
numbers smaller than `-9223372036854775808` (np.iinfo(np.int64).min)
or larger than `18446744073709551615` (np.iinfo(np.uint64).max) are
passed in, it is very likely they will be converted to float so that
they can be stored in an `ndarray`. These warnings apply similarly to
`Series` since it internally leverages `ndarray`.

Parameters
----------
arg : scalar, list, tuple, 1-d array, or Series
    Argument to be converted.

errors : {'raise', 'coerce'}, default 'raise'
    - If 'raise', then invalid parsing will raise an exception.
    - If 'coerce', then invalid parsing will be set as NaN.

downcast : str, default None
    Can be 'integer', 'signed', 'unsigned', or 'float'.
    If not None, and if the data has been successfully cast to a
    numerical dtype (or if the data was numeric to begin with),
    downcast that resulting data to the smallest numerical dtype
    possible according to the following rules:

    - 'integer' or 'signed': smallest signed int dtype (min.: np.int8)
    - 'unsigned': smallest unsigned int dtype (min.: np.uint8)
    - 'float': smallest float dtype (min.: np.float32)

    As this behaviour is separate from the core conversion to
    numeric values, any errors raised during the downcasting
    will be surfaced regardless of the value of the 'errors' input.

    In addition, downcasting will only occur if the size
    of the resulting data's dtype is strictly larger than
    the dtype it is to be cast to, so if none of the dtypes
    checked satisfy that specification, no downcasting will be
    performed on the data.

dtype_backend : {'numpy_nullable', 'pyarrow'}
    Back-end data type applied to the resultant :class:`DataFrame`
    (still experimental). If not specified, the default behavior
    is to not use nullable data types. If specified, the behavior
    is as follows:

    * ``"numpy_nullable"``: returns nullable-dtype-backed object
    * ``"pyarrow"``: returns with pyarrow-backed nullable object

    .. versionadded:: 2.0

Returns
-------
ret
    Numeric if parsing succeeded.
    Return type depends on input.  Series if Series, otherwise ndarray.

Raises
------
ValueError
    If the input contains non-numeric values and `errors='raise'`.
TypeError
    If the input is not list-like, 1D, or scalar convertible to numeric,
    such as nested lists or unsupported input types (e.g., dict).

See Also
--------
DataFrame.astype : Cast argument to a specified dtype.
to_datetime : Convert argument to datetime.
to_timedelta : Convert argument to timedelta.
numpy.ndarray.astype : Cast a numpy array to a specified type.
DataFrame.convert_dtypes : Convert dtypes.

Examples
--------
Take separate series and convert to numeric, coercing when told to

>>> s = pd.Series(["1.0", "2", -3])
>>> pd.to_numeric(s)
0    1.0
1    2.0
2   -3.0
dtype: float64
>>> pd.to_numeric(s, downcast="float")
0    1.0
1    2.0
2   -3.0
dtype: float32
>>> pd.to_numeric(s, downcast="signed")
0    1
1    2
2   -3
dtype: int8
>>> s = pd.Series(["apple", "1.0", "2", -3])
>>> pd.to_numeric(s, errors="coerce")
0    NaN
1    1.0
2    2.0
3   -3.0
dtype: float64

Downcasting of nullable integer and floating dtypes is supported:

>>> s = pd.Series([1, 2, 3], dtype="Int64")
>>> pd.to_numeric(s, downcast="integer")
0    1
1    2
2    3
dtype: Int8
>>> s = pd.Series([1.0, 2.1, 3.0], dtype="Float64")
>>> pd.to_numeric(s, downcast="float")
0    1.0
1    2.1
2    3.0
dtype: Float32
File:      c:\users\hp\appdata\local\programs\python\python312\lib\site-packages\pandas\core\tools\numeric.py
Type:      function

In [100]:
df["Age_New"]=pd.to_numeric(df['Age'],errors = "coerce")

In [102]:
df["Ticket_New"]=pd.to_numeric(df['Ticket'],errors = "coerce")

In [103]:
df

,Survived,Pclass,Dfgg,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ASD,Age_New,Ticket_New
PassengerId,,,,,,,,,,,,,,,
1,0,3,0,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,3,22.0,NaN
2,1,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,3,38.0,NaN
3,1,3,0,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,3,26.0,NaN
4,1,1,0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,3,35.0,113803.0
5,0,3,0,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,3,35.0,373450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,0,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,3,27.0,211536.0
888,1,1,0,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,3,19.0,112053.0
889,0,3,0,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,3,NaN,NaN
890,1,1,0,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,3,26.0,111369.0
891,0,3,0,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,3,32.0,370376.0

In [ ]:
df[df['Age']<10]

In [ ]:
df.astype?

In [ ]:
df['Ticket']

In [ ]:
df['Ticket'].astype("int")

In [ ]:
df['Ticket'].astype("int",errors = "ignore")

In [ ]:
pd.to_numeric(df['Ticket'])

In [ ]:
pd.to_numeric(df['Ticket'],errors='coerce')

In [ ]:
pd.to_numeric?

In [ ]:
# Convert 'Age' column to integer (int64)
df['Age'].astype('int64')

# Convert 'Sex' column to the more memory-efficient 'category' type
df['Sex'].astype('category')

# Convert a numerical column to string
df['Ticket'].astype(str)

In [ ]:
df['Sex'] = df['Sex'].astype('category')

In [ ]:
df.dtypes

In [ ]:
df['Sex'].cat.remove_categories("male")

In [ ]:
df['Sex'] = df['Sex'].cat.add_categories("other")

In [ ]:
df['Sex'].cat.remove_unused_categories()

In [ ]:
df['Sex'] = df['Sex'].cat.rename_categories({'female':'F','male':'M','other':'O'})

In [ ]:
df

In [ ]:
# Example: Convert 'Fare' which might contain placeholder strings
df['Fare'] = pd.to_numeric(df['Fare'], errors='coerce')

# Now, any non-convertible strings in 'Fare' are set to NaN.
# You can then use df.fillna() or df.drop_na() to handle them.

In [110]:
df['Name'] = df['Name'].str.replace("Miss","Miss.")

In [111]:
# Extracts the word after the comma and before the period
df['Title'] = df['Name'].str.extract('([A-Za-z]+)\.')

In [112]:
df

,Survived,Pclass,Dfgg,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ASD,Age_New,Ticket_New,Title
PassengerId,,,,,,,,,,,,,,,,
1,0,3,0,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,3,22.0,NaN,Mr
2,1,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,3,38.0,NaN,Mrs
3,1,3,0,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,3,26.0,NaN,Miss
4,1,1,0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,3,35.0,113803.0,Mrs
5,0,3,0,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,3,35.0,373450.0,Mr
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,0,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,3,27.0,211536.0,Rev
888,1,1,0,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,3,19.0,112053.0,Miss
889,0,3,0,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,3,NaN,NaN,Miss
890,1,1,0,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,3,26.0,111369.0,Mr
891,0,3,0,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,3,32.0,370376.0,Mr

In [115]:
df.dtypes

Survived        int64
Pclass          int64
Dfgg            int64
Name              str
Sex               str
Age           float64
SibSp           int64
Parch           int64
Ticket            str
Fare          float64
Cabin             str
Embarked          str
ASD             int64
Age_New       float64
Ticket_New    float64
Title             str
dtype: object

In [119]:
enumerate?

Init signature: enumerate(iterable, start=0)
Docstring:
Return an enumerate object.

  iterable
    an object supporting iteration

The enumerate object yields pairs containing a count (from start, which
defaults to zero) and a value yielded by the iterable argument.

enumerate is useful for obtaining an indexed list:
    (0, seq[0]), (1, seq[1]), (2, seq[2]), ...
Type:           type
Subclasses:

In [121]:
title_map = dict(enumerate(df["Title"].unique(),start = 1))

In [123]:
title_map = {j:i for i,j in title_map.items()}

In [125]:
df["Title_Num"] = df["Title"].map(title_map)

In [126]:
df.columns

Index(['Survived', 'Pclass', 'Dfgg', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked', 'ASD', 'Age_New', 'Ticket_New',
       'Title', 'Title_Num'],
      dtype='str')

In [130]:
df.dtypes

Survived        int64
Pclass          int64
Dfgg            int64
Name              str
Sex               str
Age           float64
SibSp           int64
Parch           int64
Ticket            str
Fare          float64
Cabin             str
Embarked          str
ASD             int64
Age_New       float64
Ticket_New    float64
Title             str
Title_Num       int64
dtype: object

In [131]:
[i for i in df.columns if df[i].dtype != "str"]

['Survived',
 'Pclass',
 'Dfgg',
 'Age',
 'SibSp',
 'Parch',
 'Fare',
 'ASD',
 'Age_New',
 'Ticket_New',
 'Title_Num']

In [132]:
df.select_dtypes(exclude="str").columns.tolist()

['Survived',
 'Pclass',
 'Dfgg',
 'Age',
 'SibSp',
 'Parch',
 'Fare',
 'ASD',
 'Age_New',
 'Ticket_New',
 'Title_Num']

In [133]:
num_cols = df.select_dtypes(include="number").columns.tolist()
print(num_cols)

['Survived', 'Pclass', 'Dfgg', 'Age', 'SibSp', 'Parch', 'Fare', 'ASD', 'Age_New', 'Ticket_New', 'Title_Num']

In [134]:
df[num_cols].corr()

,Survived,Pclass,Dfgg,Age,SibSp,Parch,Fare,ASD,Age_New,Ticket_New,Title_Num
Survived,1.000000,-0.338481,NaN,-0.077221,-0.035322,0.081629,0.257307,NaN,-0.077221,-0.122464,0.290260
Pclass,-0.338481,1.000000,NaN,-0.369226,0.083081,0.018443,-0.549500,NaN,-0.369226,0.275151,-0.191152
Dfgg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age,-0.077221,-0.369226,NaN,1.000000,-0.308247,-0.189119,0.096067,NaN,1.000000,-0.148640,-0.075120
SibSp,-0.035322,0.083081,NaN,-0.308247,1.000000,0.414838,0.159651,NaN,-0.308247,0.269342,0.148118
Parch,0.081629,0.018443,NaN,-0.189119,0.414838,1.000000,0.216225,NaN,-0.189119,0.088722,0.137145
Fare,0.257307,-0.549500,NaN,0.096067,0.159651,0.216225,1.000000,NaN,0.096067,-0.139868,0.108309
ASD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age_New,-0.077221,-0.369226,NaN,1.000000,-0.308247,-0.189119,0.096067,NaN,1.000000,-0.148640,-0.075120
Ticket_New,-0.122464,0.275151,NaN,-0.148640,0.269342,0.088722,-0.139868,NaN,-0.148640,1.000000,-0.019109
Title_Num,0.290260,-0.191152,NaN,-0.075120,0.148118,0.137145,0.108309,NaN,-0.075120,-0.019109,1.000000

In [ ]:
# Convert a standard date string column
df['Date'] = pd.to_datetime(df['DateString'])

In [ ]:
Code,  Meaning,          Example
%Y,    Year with century,2025
%m,    Month as a number,12
%d,    Day of the month,  15
%b,    Abbreviated month name,Dec

In [ ]:
# Example for a date string like '15-12-2025'
df['PurchaseDate'] = pd.to_datetime(
    df['PurchaseDate'], 
    format='%d-%m-%Y'
)

In [105]:
df['Title']

PassengerId
1       Mr
2      Mrs
3      NaN
4      Mrs
5       Mr
      ...
887    Rev
888    NaN
889    NaN
890     Mr
891     Mr
Name: Title, Length: 891, dtype: str

In [ ]:
Attribute,Purpose,Example
.dt.year,Extracts the year as an integer.,df['Date'].dt.year
.dt.month,Extracts the month (1-12).,df['Date'].dt.month
.dt.day,Extracts the day of the month.,df['Date'].dt.day
.dt.day_name(),"Extracts the weekday name (e.g., 'Monday').",df['Date'].dt.day_name()
.dt.is_leap_year,Returns a boolean (True/False).,df['Date'].dt.is_leap_year

In [ ]:
# Extracts the week of the year (01-52)
df['Week_of_Year'] = df['OrderDate'].dt.isocalendar().week

# Filters for data in the first quarter (Jan, Feb, Mar)
q1_data = df[df['OrderDate'].dt.quarter == 1]

In [ ]:
# Convert to 'category' type first
df['Severity'] = df['Severity'].astype('category')

# Define the logical order
new_order = ['Low', 'Medium', 'High', 'Critical']

# Apply the new order
df['Severity'] = df['Severity'].cat.reorder_categories(new_order, ordered=True)

In [135]:
# Calculate the average Fare paid by passengers in each Pclass (1st, 2nd, 3rd)
df.groupby('Pclass')['Fare'].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [136]:
# Group by 'Pclass' and calculate:
# 1. The min and max of 'Age'
# 2. The sum of 'Fare'
grouped_stats = df.groupby('Pclass').agg(
    {
        'Age': ['min', 'max'],
        'Fare': 'sum'
    }
)

In [137]:
grouped_stats

         Age              Fare
         min   max         sum
Pclass
1       0.92  80.0  18177.4125
2       0.67  70.0   3801.8417
3       0.42  74.0   6714.6951

In [139]:
df['Pclass'].value_counts().sort_index()

Pclass
1    216
2    184
3    491
Name: count, dtype: int64

In [140]:
df.isna().sum()

Survived        0
Pclass          0
Dfgg            0
Name            0
Sex             0
Age           177
SibSp           0
Parch           0
Ticket          0
Fare            0
Cabin         687
Embarked        2
ASD             0
Age_New       177
Ticket_New    230
Title          40
Title_Num       0
dtype: int64

In [141]:
df.isnull().sum()

Survived        0
Pclass          0
Dfgg            0
Name            0
Sex             0
Age           177
SibSp           0
Parch           0
Ticket          0
Fare            0
Cabin         687
Embarked        2
ASD             0
Age_New       177
Ticket_New    230
Title          40
Title_Num       0
dtype: int64

# Missing Data

In [142]:
df.isna().sum()

Survived        0
Pclass          0
Dfgg            0
Name            0
Sex             0
Age           177
SibSp           0
Parch           0
Ticket          0
Fare            0
Cabin         687
Embarked        2
ASD             0
Age_New       177
Ticket_New    230
Title          40
Title_Num       0
dtype: int64

In [149]:
df.isna().mean()*100

Survived       0.000000
Pclass         0.000000
Dfgg           0.000000
Name           0.000000
Sex            0.000000
Age           19.865320
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
Cabin         77.104377
Embarked       0.224467
ASD            0.000000
Age_New       19.865320
Ticket_New     0.448934
Title          4.489338
Title_Num      0.000000
dtype: float64

In [148]:
df['Ticket_New'] = df['Ticket'].str.extract(r"\b(\d+)")

In [151]:
df[df['Ticket_New'].isna()][['Ticket_New','Ticket']]

            Ticket_New Ticket
PassengerId
180                NaN   LINE
272                NaN   LINE
303                NaN   LINE
598                NaN   LINE

In [154]:
df

,Survived,Pclass,Dfgg,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ASD,Age_New,Ticket_New,Title,Title_Num
PassengerId,,,,,,,,,,,,,,,,,
1,0,3,0,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,3,22.0,5,Mr,1
2,1,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,3,38.0,17599,Mrs,2
3,1,3,0,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,3,26.0,3101282,Miss,3
4,1,1,0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,3,35.0,113803,Mrs,2
5,0,3,0,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,3,35.0,373450,Mr,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,0,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,3,27.0,211536,Rev,6
888,1,1,0,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,3,19.0,112053,Miss,3
889,0,3,0,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,3,NaN,6607,Miss,3
890,1,1,0,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,3,26.0,111369,Mr,1
891,0,3,0,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,3,32.0,370376,Mr,1

In [155]:
df['Ticket_New'] = df['Ticket_New'].fillna("Ticket Number Not Available")

In [158]:
df.at[1,'Ticket_New'] = '21171'

In [159]:
df

,Survived,Pclass,Dfgg,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ASD,Age_New,Ticket_New,Title,Title_Num
PassengerId,,,,,,,,,,,,,,,,,
1,0,3,0,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,3,22.0,21171,Mr,1
2,1,1,0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,3,38.0,17599,Mrs,2
3,1,3,0,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,3,26.0,3101282,Miss,3
4,1,1,0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,3,35.0,113803,Mrs,2
5,0,3,0,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,3,35.0,373450,Mr,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,0,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,3,27.0,211536,Rev,6
888,1,1,0,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,3,19.0,112053,Miss,3
889,0,3,0,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,3,NaN,6607,Miss,3
890,1,1,0,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,3,26.0,111369,Mr,1
891,0,3,0,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,3,32.0,370376,Mr,1

In [165]:
df["Embarked_Full"] = df["Embarked"].dropna()

In [166]:
df[df["Embarked_Full"].isna() ]

,Survived,Pclass,Dfgg,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ASD,Age_New,Ticket_New,Title,Title_Num,Embarked_Full
PassengerId,,,,,,,,,,,,,,,,,,
62,1,1,0,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0,B28,NaN,3,38.0,113572,Miss,3,NaN
830,1,1,0,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0,B28,NaN,3,62.0,113572,Mrs,2,NaN

In [168]:
df1 = df.dropna(subset = "Embarked_Full")

In [162]:
df.dropna?

Signature:
df.dropna(
    *,
    axis: 'Axis' = 0,
    how: 'AnyAll | lib.NoDefault' = <no_default>,
    thresh: 'int | lib.NoDefault' = <no_default>,
    subset: 'IndexLabel | AnyArrayLike | None' = None,
    inplace: 'bool' = False,
    ignore_index: 'bool' = False,
) -> 'DataFrame | None'
Docstring:
Remove missing values.

See the :ref:`User Guide <missing_data>` for more on which values are
considered missing, and how to work with missing data.

Parameters
----------
axis : {0 or 'index', 1 or 'columns'}, default 0
    Determine if rows or columns which contain missing values are
    removed.

    * 0, or 'index' : Drop rows which contain missing values.
    * 1, or 'columns' : Drop columns which contain missing value.

    Only a single axis is allowed.

how : {'any', 'all'}, default 'any'
    Determine if row or column is removed from DataFrame, when we have
    at least one NA or all NA.

    * 'any' : If any NA values are present, drop that row or column.
    * 'all' : If all values are NA, drop that row or column.

thresh : int, optional
    Require that many non-NA values. Cannot be combined with how.
subset : column label or iterable of labels, optional
    Labels along other axis to consider, e.g. if you are dropping rows
    these would be a list of columns to include.
inplace : bool, default False
    Whether to modify the DataFrame rather than creating a new one.
ignore_index : bool, default ``False``
    If ``True``, the resulting axis will be labeled 0, 1, …, n - 1.

    .. versionadded:: 2.0.0

Returns
-------
DataFrame or None
    DataFrame with NA entries dropped from it or None if ``inplace=True``.

See Also
--------
DataFrame.isna: Indicate missing values.
DataFrame.notna : Indicate existing (non-missing) values.
DataFrame.fillna : Replace missing values.
Series.dropna : Drop missing values.
Index.dropna : Drop missing indices.

Examples
--------
>>> df = pd.DataFrame(
...     {
...         "name": ["Alfred", "Batman", "Catwoman"],
...         "toy": [np.nan, "Batmobile", "Bullwhip"],
...         "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT],
...     }
... )
>>> df
       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

Drop the rows where at least one element is missing.

>>> df.dropna()
     name        toy       born
1  Batman  Batmobile 1940-04-25

Drop the columns where at least one element is missing.

>>> df.dropna(axis="columns")
       name
0    Alfred
1    Batman
2  Catwoman

Drop the rows where all elements are missing.

>>> df.dropna(how="all")
       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

Keep only the rows with at least 2 non-NA values.

>>> df.dropna(thresh=2)
       name        toy       born
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

Define in which columns to look for missing values.

>>> df.dropna(subset=["name", "toy"])
       name        toy       born
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT
File:      c:\users\hp\appdata\local\programs\python\python312\lib\site-packages\pandas\core\frame.py
Type:      method

In [161]:
df['Embarked'].drop_na?

Object `drop_na` not found.

In [ ]:
df[df['Embarked'].isna()]

In [ ]:
df['Embarked'].unique()

In [ ]:
df.dropna(how="any",axis=1)

In [ ]:
df['Embarked_fill']=df['Embarked'].fillna("Data Missing")

In [ ]:
df

In [ ]:
df['Embarked'].unique()

In [ ]:
df['Embarked_fill'].unique()

In [ ]:
df[df['Embarked'].isnull()]

In [ ]:
embares=df.loc[[60,61,62,63,64,65,828,829,830,831,832],:]

In [ ]:
embares['Embarked'].fillna(method='ffill')

In [ ]:
embares['Embarked'].fillna(method='bfill')

In [ ]:
df['Embarked'].mode()

In [ ]:
df['Embarked'].fillna("S").unique()

In [ ]:
# Filters the DataFrame to show only rows where 'Age' is null
missing_age_rows = df[df['Age'].isnull()]

In [ ]:
# Fills all missing 'Cabin' values with the string 'Unknown'
df['Cabin'].fillna('Unknown', inplace=True)

In [ ]:
# Calculate the median of the 'Age' column
age_median = df['Age'].median()

# Fill the missing 'Age' values with the calculated median
df['Age'].fillna(age_median, inplace=True)

Method,Description,Example
method='ffill',Forward Fill: Replaces null with the previous non-null value.,"df['StockPrice'].fillna(method='ffill', inplace=True)"
method='bfill',Backward Fill: Replaces null with the next non-null value.,"df['StockPrice'].fillna(method='bfill', inplace=True)"