In [1]:
import pandas as pd
import numpy as np

# Series

In [2]:
pd.Series?

Init signature:
pd.Series(
    data=None,
    index=None,
    dtype: 'Dtype | None' = None,
    name=None,
    copy: 'bool | None' = None,
) -> 'None'
Docstring:
One-dimensional ndarray with axis labels (including time series).

Labels need not be unique but must be a hashable type. The object
supports both integer- and label-based indexing and provides a host of
methods for performing operations involving the index. Statistical
methods from ndarray have been overridden to automatically exclude
missing data (currently represented as NaN).

Operations between Series (+, -, /, \*, \*\*) align values based on their
associated index values-- they need not be the same length. The result
index will be the sorted union of the two indexes.

Parameters
----------
data : array-like, Iterable, dict, or scalar value
    Contains data stored in Series. If data is a dict, argument order is
    maintained. Unordered sets are not supported.
index : array-like or Index (1d)
    Values must be hashable and have the same length as `data`.
    Non-unique index values are allowed. Will default to
    RangeIndex (0, 1, 2, ..., n) if not provided. If data is dict-like
    and index is None, then the keys in the data are used as the index. If the
    index is not None, the resulting Series is reindexed with the index values.
dtype : str, numpy.dtype, or ExtensionDtype, optional
    Data type for the output Series. If not specified, this will be
    inferred from `data`.
    See the :ref:`user guide <basics.dtypes>` for more usages.
name : Hashable, default None
    The name to give to the Series.
copy : bool, default None
    Whether to copy input data, only relevant for array, Series, and Index
    inputs (for other input, e.g. a list, a new array is created anyway).
    Defaults to True for array input and False for Index/Series.
    Even when False for Index/Series, a shallow copy of the data is made.
    Set to False to avoid copying array input at your own risk (if you
    know the input data won't be modified elsewhere).
    Set to True to force copying Series/Index input up front.

See Also
--------
DataFrame : Two-dimensional, size-mutable, potentially heterogeneous tabular data.
Index : Immutable sequence used for indexing and alignment.

Notes
-----
Please reference the :ref:`User Guide <basics.series>` for more information.

Examples
--------
Constructing Series from a dictionary with an Index specified

>>> d = {"a": 1, "b": 2, "c": 3}
>>> ser = pd.Series(data=d, index=["a", "b", "c"])
>>> ser
a   1
b   2
c   3
dtype: int64

The keys of the dictionary match with the Index values, hence the Index
values have no effect.

>>> d = {"a": 1, "b": 2, "c": 3}
>>> ser = pd.Series(data=d, index=["x", "y", "z"])
>>> ser
x   NaN
y   NaN
z   NaN
dtype: float64

Note that the Index is first built with the keys from the dictionary.
After this the Series is reindexed with the given Index values, hence we
get all NaN as a result.

Constructing Series from a list with `copy=False`.

>>> r = [1, 2]
>>> ser = pd.Series(r, copy=False)
>>> ser.iloc[0] = 999
>>> r
[1, 2]
>>> ser
0    999
1      2
dtype: int64

Due to input data type the Series has a `copy` of
the original data even though `copy=False`, so
the data is unchanged.

Constructing Series from a 1d ndarray with `copy=False`.

>>> r = np.array([1, 2])
>>> ser = pd.Series(r, copy=False)
>>> ser.iloc[0] = 999
>>> r
array([999,   2])
>>> ser
0    999
1      2
dtype: int64

Due to input data type the Series has a `view` on
the original data, so
the data is changed as well.
File:           c:\users\hp\appdata\local\programs\python\python312\lib\site-packages\pandas\__init__.py
Type:           type
Subclasses:     SubclassedSeries

In [3]:
ser1 = pd.Series([1,2,3,4,5,6])

In [4]:
ser1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [5]:
type(ser1)

pandas.Series

In [6]:
ser1[5]

np.int64(6)

In [7]:
ser1[2:4] # integer based indexing

2    3
3    4
dtype: int64

In [8]:
ser1.max()

np.int64(6)

In [9]:
ser1.min()

np.int64(1)

In [10]:
ser1.mean()

np.float64(3.5)

In [11]:
ser2 = pd.Series([1,2,3,4],["A","B","C","D"])

In [12]:
ser2

A    1
B    2
C    3
D    4
dtype: int64

In [13]:
ser2["A"]

np.int64(1)

In [14]:
ser2["A":"D"] # last item included#label

A    1
B    2
C    3
D    4
dtype: int64

In [15]:
ser2[0]

KeyError: 0

In [17]:
ser2.iat[0]

np.int64(1)

In [18]:
ser2.at[0]

KeyError: 0

In [19]:
ser3=pd.Series([1,2,3],dtype=str)

In [20]:
ser3

0    1
1    2
2    3
dtype: str

In [21]:
ser3[0]+ser3[1]

'12'

# DataFrame

In [22]:
dic1 = {"name":"Shubham","age":29}

In [23]:
dic1["name"]

'Shubham'

In [24]:
df = pd.DataFrame(dic1,index=["Record1"])

In [25]:
df

            name  age
Record1  Shubham   29

In [26]:
df["name"]

Record1    Shubham
Name: name, dtype: str

In [27]:
df["age"]

Record1    29
Name: age, dtype: int64

In [28]:
df[["age"]]

         age
Record1   29

In [29]:
df.columns

Index(['name', 'age'], dtype='str')

In [30]:
df.index

Index(['Record1'], dtype='str')

In [31]:
df = pd.DataFrame(
    {
        "Name": [
            "Braund, Mr. Owen Harris",
            "Allen, Mr. William Henry",
            "Bonnell, Miss. Elizabeth",
        ],
        "Age": [22, 35, 58],
        "Sex": ["male", "male", "female"],
    }
)

In [32]:
df

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2  Bonnell, Miss. Elizabeth   58  female

In [33]:
df.columns

Index(['Name', 'Age', 'Sex'], dtype='str')

In [34]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [35]:
df

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2  Bonnell, Miss. Elizabeth   58  female

In [36]:
df.loc[1,'Name']

'Allen, Mr. William Henry'

In [37]:
df.loc[2,:]

Name    Bonnell, Miss. Elizabeth
Age                           58
Sex                       female
Name: 2, dtype: object

In [38]:
df

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2  Bonnell, Miss. Elizabeth   58  female

In [39]:
df.loc[1:2,:] # lables means name

                       Name  Age     Sex
1  Allen, Mr. William Henry   35    male
2  Bonnell, Miss. Elizabeth   58  female

In [40]:
df

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2  Bonnell, Miss. Elizabeth   58  female

In [41]:
df.iloc[1:2,:] # inter based index number

                       Name  Age   Sex
1  Allen, Mr. William Henry   35  male

In [42]:
df

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2  Bonnell, Miss. Elizabeth   58  female

In [43]:
df.iloc[1:2,1]

1    35
Name: Age, dtype: int64

In [44]:
df.loc[1:2,"Age"]

1    35
2    58
Name: Age, dtype: int64

In [45]:
df[["Age","Name"]] # dataframe

   Age                      Name
0   22   Braund, Mr. Owen Harris
1   35  Allen, Mr. William Henry
2   58  Bonnell, Miss. Elizabeth

In [46]:
type(df)

pandas.DataFrame

In [47]:
type(df[["Age","Name"]]) # dataframe

pandas.DataFrame

In [48]:
type(df["Age"])

pandas.Series

In [49]:
type(df[["Age"]])

pandas.DataFrame

In [50]:
df[["Age"]]

   Age
0   22
1   35
2   58

In [51]:
df["Age"]

0    22
1    35
2    58
Name: Age, dtype: int64

In [52]:
df

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2  Bonnell, Miss. Elizabeth   58  female

In [53]:
df.at[1,"Age"]

np.int64(35)

In [54]:
df.at[2,"Age"]

np.int64(58)

In [55]:
df

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2  Bonnell, Miss. Elizabeth   58  female

In [56]:
df.iat[2,2]

'female'

In [57]:
df

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2  Bonnell, Miss. Elizabeth   58  female

In [58]:
df.iat[2,2]='male'

In [59]:
df

                       Name  Age   Sex
0   Braund, Mr. Owen Harris   22  male
1  Allen, Mr. William Henry   35  male
2  Bonnell, Miss. Elizabeth   58  male

In [60]:
df.iloc[1:,2]=["male","female"]

In [61]:
df

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2  Bonnell, Miss. Elizabeth   58  female

In [62]:
df.at[1,"Name"]=np.nan

In [63]:
df

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1                       NaN   35    male
2  Bonnell, Miss. Elizabeth   58  female

In [71]:
df.index=[1,2,3]

In [72]:
df

                       Name  Age     Sex
1   Braund, Mr. Owen Harris   22    male
2                       NaN   35    male
3  Bonnell, Miss. Elizabeth   58  female

In [73]:
df.at[1,"Sex"]

'male'

In [74]:
df

                       Name  Age     Sex
1   Braund, Mr. Owen Harris   22    male
2                       NaN   35    male
3  Bonnell, Miss. Elizabeth   58  female

In [75]:
df.loc[1:3,"Age"]

1    22
2    35
3    58
Name: Age, dtype: int64

In [76]:
df.iloc[1:3,1]

2    35
3    58
Name: Age, dtype: int64

In [77]:
df

                       Name  Age     Sex
1   Braund, Mr. Owen Harris   22    male
2                       NaN   35    male
3  Bonnell, Miss. Elizabeth   58  female

In [78]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, 1 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     3 non-null      int64
 2   Sex     3 non-null      str
dtypes: int64(1), str(2)
memory usage: 266.0 bytes

In [79]:
df.describe() # short statistical summary of numeric column only

             Age
count   3.000000
mean   38.333333
std    18.230012
min    22.000000
25%    28.500000
50%    35.000000
75%    46.500000
max    58.000000

In [80]:
df.head?

Signature: df.head(n: 'int' = 5) -> 'Self'
Docstring:
Return the first `n` rows.

This function exhibits the same behavior as ``df[:n]``, returning the
first ``n`` rows based on position. It is useful for quickly checking
if your object has the right type of data in it.

When ``n`` is positive, it returns the first ``n`` rows. For ``n`` equal to 0,
it returns an empty object. When ``n`` is negative, it returns
all rows except the last ``|n|`` rows, mirroring the behavior of ``df[:n]``.

If ``n`` is larger than the number of rows, this function returns all rows.

Parameters
----------
n : int, default 5
    Number of rows to select.

Returns
-------
same type as caller
    The first `n` rows of the caller object.

See Also
--------
DataFrame.tail: Returns the last `n` rows.

Examples
--------
>>> df = pd.DataFrame(
...     {
...         "animal": [
...             "alligator",
...             "bee",
...             "falcon",
...             "lion",
...             "monkey",
...             "parrot",
...             "shark",
...             "whale",
...             "zebra",
...         ]
...     }
... )
>>> df
      animal
0  alligator
1        bee
2     falcon
3       lion
4     monkey
5     parrot
6      shark
7      whale
8      zebra

Viewing the first 5 lines

>>> df.head()
      animal
0  alligator
1        bee
2     falcon
3       lion
4     monkey

Viewing the first `n` lines (three in this case)

>>> df.head(3)
      animal
0  alligator
1        bee
2     falcon

For negative values of `n`

>>> df.head(-3)
      animal
0  alligator
1        bee
2     falcon
3       lion
4     monkey
5     parrot
File:      c:\users\hp\appdata\local\programs\python\python312\lib\site-packages\pandas\core\generic.py
Type:      method

In [81]:
df

                       Name  Age     Sex
1   Braund, Mr. Owen Harris   22    male
2                       NaN   35    male
3  Bonnell, Miss. Elizabeth   58  female

In [82]:
df.head() # 5 record

                       Name  Age     Sex
1   Braund, Mr. Owen Harris   22    male
2                       NaN   35    male
3  Bonnell, Miss. Elizabeth   58  female

In [83]:
df.head(2)

                      Name  Age   Sex
1  Braund, Mr. Owen Harris   22  male
2                      NaN   35  male

In [84]:
df.head(-2)

                      Name  Age   Sex
1  Braund, Mr. Owen Harris   22  male

In [85]:
df.tail()

                       Name  Age     Sex
1   Braund, Mr. Owen Harris   22    male
2                       NaN   35    male
3  Bonnell, Miss. Elizabeth   58  female

In [86]:
df.tail(1)

                       Name  Age     Sex
3  Bonnell, Miss. Elizabeth   58  female

In [89]:
df.sample?

Signature:
df.sample(
    n: 'int | None' = None,
    frac: 'float | None' = None,
    replace: 'bool' = False,
    weights=None,
    random_state: 'RandomState | None' = None,
    axis: 'Axis | None' = None,
    ignore_index: 'bool' = False,
) -> 'Self'
Docstring:
Return a random sample of items from an axis of object.

You can use `random_state` for reproducibility.

Parameters
----------
n : int, optional
    Number of items from axis to return. Cannot be used with `frac`.
    Default = 1 if `frac` = None.
frac : float, optional
    Fraction of axis items to return. Cannot be used with `n`.
replace : bool, default False
    Allow or disallow sampling of the same row more than once.
weights : str or ndarray-like, optional
    Default ``None`` results in equal probability weighting.
    If passed a Series, will align with target object on index. Index
    values in weights not found in sampled object will be ignored and
    index values in sampled object not in weights will be assigned
    weights of zero.
    If called on a DataFrame, will accept the name of a column
    when axis = 0.
    Unless weights are a Series, weights must be same length as axis
    being sampled.
    If weights do not sum to 1, they will be normalized to sum to 1.
    Missing values in the weights column will be treated as zero.
    Infinite values not allowed.
    When replace = False will not allow ``(n * max(weights) / sum(weights)) > 1``
    in order to avoid biased results. See the Notes below for more details.
random_state : int, array-like, BitGenerator, np.random.RandomState, np.random.Generator, optional
    If int, array-like, or BitGenerator, seed for random number generator.
    If np.random.RandomState or np.random.Generator, use as given.
    Default ``None`` results in sampling with the current state of np.random.
axis : {0 or 'index', 1 or 'columns', None}, default None
    Axis to sample. Accepts axis number or name. Default is stat axis
    for given data type. For `Series` this parameter is unused and defaults to `None`.
ignore_index : bool, default False
    If True, the resulting index will be labeled 0, 1, …, n - 1.

Returns
-------
Series or DataFrame
    A new object of same type as caller containing `n` items randomly
    sampled from the caller object.

See Also
--------
DataFrameGroupBy.sample: Generates random samples from each group of a
    DataFrame object.
SeriesGroupBy.sample: Generates random samples from each group of a
    Series object.
numpy.random.choice: Generates a random sample from a given 1-D numpy
    array.

Notes
-----
If `frac` > 1, `replacement` should be set to `True`.

When replace = False will not allow ``(n * max(weights) / sum(weights)) > 1``,
since that would cause results to be biased. E.g. sampling 2 items without replacement
with weights [100, 1, 1] would yield two last items in 1/2 of cases, instead of 1/102.
This is similar to specifying `n=4` without replacement on a Series with 3 elements.

Examples
--------
>>> df = pd.DataFrame(
...     {
...         "num_legs": [2, 4, 8, 0],
...         "num_wings": [2, 0, 0, 0],
...         "num_specimen_seen": [10, 2, 1, 8],
...     },
...     index=["falcon", "dog", "spider", "fish"],
... )
>>> df
        num_legs  num_wings  num_specimen_seen
falcon         2          2                 10
dog            4          0                  2
spider         8          0                  1
fish           0          0                  8

Extract 3 random elements from the ``Series`` ``df['num_legs']``:
Note that we use `random_state` to ensure the reproducibility of
the examples.

>>> df["num_legs"].sample(n=3, random_state=1)
fish      0
spider    8
falcon    2
Name: num_legs, dtype: int64

A random 50% sample of the ``DataFrame`` with replacement:

>>> df.sample(frac=0.5, replace=True, random_state=1)
      num_legs  num_wings  num_specimen_seen
dog          4          0                  2
fish         0          0                  8

An upsample sample of the ``DataFrame`` with replacement:
Note that `replace` parameter has to be `True` for `frac` parameter > 1.

>>> df.sample(frac=2, replace=True, random_state=1)
        num_legs  num_wings  num_specimen_seen
dog            4          0                  2
fish           0          0                  8
falcon         2          2                 10
falcon         2          2                 10
fish           0          0                  8
dog            4          0                  2
fish           0          0                  8
dog            4          0                  2

Using a DataFrame column as weights. Rows with larger value in the
`num_specimen_seen` column are more likely to be sampled.

>>> df.sample(n=2, weights="num_specimen_seen", random_state=1)
        num_legs  num_wings  num_specimen_seen
falcon         2          2                 10
fish           0          0                  8
File:      c:\users\hp\appdata\local\programs\python\python312\lib\site-packages\pandas\core\generic.py
Type:      method

In [87]:
df.sample() # defacult

                       Name  Age     Sex
3  Bonnell, Miss. Elizabeth   58  female

In [91]:
df.sample(2)

                       Name  Age     Sex
3  Bonnell, Miss. Elizabeth   58  female
2                       NaN   35    male

In [92]:
df.nunique()

Name    2
Age     3
Sex     2
dtype: int64

In [93]:
df["Sex"].nunique()

2

In [94]:
df["Sex"].unique()

<ArrowStringArray>
['male', 'female']
Length: 2, dtype: str

In [95]:
df

                       Name  Age     Sex
1   Braund, Mr. Owen Harris   22    male
2                       NaN   35    male
3  Bonnell, Miss. Elizabeth   58  female

In [96]:
df.T

                            1     2                         3
Name  Braund, Mr. Owen Harris   NaN  Bonnell, Miss. Elizabeth
Age                        22    35                        58
Sex                      male  male                    female

In [97]:
df.to_csv("test1.csv",index=False)

In [98]:
df.to_json("test1.json",index=False)

In [99]:
df1 = pd.read_csv("test1.csv")

In [100]:
df1

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1                       NaN   35    male
2  Bonnell, Miss. Elizabeth   58  female

In [103]:
df2 = pd.read_json("test1.json")

In [104]:
df2

                       Name  Age     Sex
1   Braund, Mr. Owen Harris   22    male
2                   Shubham   35    male
3  Bonnell, Miss. Elizabeth   58  female

In [105]:
df3 = pd.read_csv("shubham.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'shubham.csv'