In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_excel("Titanic.xlsx",sheet_name="Titanic")

In [4]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df.set_index?

In [5]:
df.set_index("PassengerId")

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [6]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [7]:
df.set_index("PassengerId",inplace = True)

In [8]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [9]:
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [10]:
df.head(10)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [11]:
df.tail()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [12]:
df.tail(10)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
883,0,3,"Dahlberg, Miss Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [13]:
df.sample()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
304,1,2,"Keane, Miss Nora A",female,NaN,0,0,226593,12.35,E101,Q

In [14]:
df.sample(10)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
350,0,3,"Dimic, Mr. Jovan",male,42.0,0,0,315088,8.6625,NaN,S
735,0,2,"Troupiansky, Mr. Moses Aaron",male,23.0,0,0,233639,13.0000,NaN,S
688,0,3,"Dakic, Mr. Branko",male,19.0,0,0,349228,10.1708,NaN,S
471,0,3,"Keefe, Mr. Arthur",male,NaN,0,0,323592,7.2500,NaN,S
33,1,3,"Glynn, Miss Mary Agatha",female,NaN,0,0,335677,7.7500,NaN,Q
159,0,3,"Smiljanic, Mr. Mile",male,NaN,0,0,315037,8.6625,NaN,S
721,1,2,"Harper, Miss Annie Jessie ""Nina""",female,6.0,0,1,248727,33.0000,NaN,S
114,0,3,"Jussila, Miss Katriina",female,20.0,1,0,4136,9.8250,NaN,S
711,1,1,"Mayne, Mlle. Berthe Antonine (""Mrs de Villiers"")",female,24.0,0,0,PC 17482,49.5042,C90,C

In [15]:
clos =df.columns

In [16]:
clos

Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket',
       'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [17]:
rows = df.index

In [18]:
rows

RangeIndex(start=1, stop=892, step=1, name='PassengerId')

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 1 to 891
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Name      891 non-null    str
 3   Sex       891 non-null    str
 4   Age       714 non-null    float64
 5   SibSp     891 non-null    int64
 6   Parch     891 non-null    int64
 7   Ticket    891 non-null    str
 8   Fare      891 non-null    float64
 9   Cabin     204 non-null    str
 10  Embarked  889 non-null    str
dtypes: float64(2), int64(4), str(5)
memory usage: 111.7 KB

In [20]:
df.shape

(891, 11)

In [21]:
rows_count = df.shape[0]

In [22]:
rows_count

891

In [23]:
columns_count = df.shape[1]

In [24]:
columns_count

11

In [25]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [26]:
df.describe()

         Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [27]:
df['Age']

PassengerId
1      22.0
2      38.0
3      26.0
4      35.0
5      35.0
       ...
887    27.0
888    19.0
889     NaN
890    26.0
891    32.0
Name: Age, Length: 891, dtype: float64

In [28]:
df[["Age"]]

              Age
PassengerId
1            22.0
2            38.0
3            26.0
4            35.0
5            35.0
...           ...
887          27.0
888          19.0
889           NaN
890          26.0
891          32.0

[891 rows x 1 columns]

In [29]:
df[["Age","Pclass"]]

              Age  Pclass
PassengerId
1            22.0       3
2            38.0       1
3            26.0       3
4            35.0       1
5            35.0       3
...           ...     ...
887          27.0       2
888          19.0       1
889           NaN       3
890          26.0       1
891          32.0       3

[891 rows x 2 columns]

In [30]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [31]:
df.loc[6,:]

Survived                   0
Pclass                     3
Name        Moran, Mr. James
Sex                     male
Age                      NaN
SibSp                      0
Parch                      0
Ticket                330877
Fare                  8.4583
Cabin                    NaN
Embarked                   Q
Name: 6, dtype: object

In [32]:
df.loc[6,"Age"]

np.float64(nan)

In [33]:
df.loc[5:10,"Age":]

              Age  SibSp  Parch  Ticket     Fare Cabin Embarked
PassengerId
5            35.0      0      0  373450   8.0500   NaN        S
6             NaN      0      0  330877   8.4583   NaN        Q
7            54.0      0      0   17463  51.8625   E46        S
8             2.0      3      1  349909  21.0750   NaN        S
9            27.0      0      2  347742  11.1333   NaN        S
10           14.0      1      0  237736  30.0708   NaN        C

In [34]:
df.iloc[5:10,4:]

              Age  SibSp  Parch  Ticket     Fare Cabin Embarked
PassengerId
6             NaN      0      0  330877   8.4583   NaN        Q
7            54.0      0      0   17463  51.8625   E46        S
8             2.0      3      1  349909  21.0750   NaN        S
9            27.0      0      2  347742  11.1333   NaN        S
10           14.0      1      0  237736  30.0708   NaN        C

In [35]:
df.iloc[6,4]

np.float64(54.0)

In [36]:
df.iloc[[5,9,8,4,10],:]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
11,1,3,"Sandstrom, Miss Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S

In [37]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 1 to 891
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Name      891 non-null    str
 3   Sex       891 non-null    str
 4   Age       714 non-null    float64
 5   SibSp     891 non-null    int64
 6   Parch     891 non-null    int64
 7   Ticket    891 non-null    str
 8   Fare      891 non-null    float64
 9   Cabin     204 non-null    str
 10  Embarked  889 non-null    str
dtypes: float64(2), int64(4), str(5)
memory usage: 111.7 KB

In [ ]:
df.nunique()

In [38]:
df["Survived"].unique()

array([0, 1])

In [39]:
df["Embarked"].unique()

<ArrowStringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

In [40]:
df.isnull()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,False,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...
887,False,False,False,False,False,False,False,False,False,True,False
888,False,False,False,False,False,False,False,False,False,False,False
889,False,False,False,False,True,False,False,False,False,True,False
890,False,False,False,False,False,False,False,False,False,False,False
891,False,False,False,False,False,False,False,False,False,True,False

In [41]:
df.isnull().sum()

Survived      0
Pclass        0
Name          0
Sex           0
Age         177
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [42]:
df.isnull().mean()*100

Survived     0.000000
Pclass       0.000000
Name         0.000000
Sex          0.000000
Age         19.865320
SibSp        0.000000
Parch        0.000000
Ticket       0.000000
Fare         0.000000
Cabin       77.104377
Embarked     0.224467
dtype: float64

In [43]:
df["Age"]>70

PassengerId
1      False
2      False
3      False
4      False
5      False
       ...
887    False
888    False
889    False
890    False
891    False
Name: Age, Length: 891, dtype: bool

In [44]:
df[df["Age"]>70] # boolean filtering

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [45]:
df[(df["Age"]>70) | (df["Age"]<10)]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
8,0,3,"Palsson, Master Gosta Leonard",male,2.00,3,1,349909,21.0750,NaN,S
11,1,3,"Sandstrom, Miss Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S
17,0,3,"Rice, Master Eugene",male,2.00,4,1,382652,29.1250,NaN,Q
25,0,3,"Palsson, Miss Torborg Danira",female,8.00,3,1,349909,21.0750,NaN,S
44,1,2,"Laroche, Miss Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...
832,1,2,"Richards, Master George Sibley",male,0.83,1,1,29106,18.7500,NaN,S
851,0,3,"Andersson, Master Sigvard Harald Elias",male,4.00,4,2,347082,31.2750,NaN,S
852,0,3,"Svensson, Mr. Johan",male,74.00,0,0,347060,7.7750,NaN,S
853,0,3,"Boulos, Miss Nourelain",female,9.00,1,1,2678,15.2458,NaN,C
870,1,3,"Johnson, Master Harold Theodor",male,4.00,1,1,347742,11.1333,NaN,S

In [ ]:
df

In [ ]:
df["ASD"] = 1+2

In [ ]:
df

In [ ]:
df.insert?

In [ ]:
df.insert(2,"dfgg",0)

In [ ]:
df

In [ ]:
df.sort_values?

In [ ]:
df.sort_values(by="Age")

In [ ]:
df.sort_index?

In [ ]:
df.sort_values(by="Age",ascending=False)

In [ ]:
df.sort_values(by=["Sex","Age"],ascending=[True,False])

In [ ]:
df.sort_index(ascending= False)

In [ ]:
ord("d")

In [ ]:
ord("T")

In [ ]:
# axis=1 refers to columns
df.sort_index(axis=1,ascending=False)

In [ ]:
# Select only passengers older than 30
adults = df[df['Age'] > 30]

In [ ]:
adults

In [ ]:
# Select females AND passengers in 1st class
rich_females = df[(df['Sex'] == 'female') & (df['Pclass'] == 1)]

# Select passengers who paid more than $100 OR are in 1st class
high_value = df[(df['Fare'] > 100) | (df['Pclass'] == 1)]

In [ ]:
rich_females

In [ ]:
# Select passengers embarking from Southampton (S) or Cherbourg (C)
ports = df[df['Embarked'].isin(['S', 'C'])]

In [ ]:
ports

In [ ]:
# Select anyone with "Mr." in their name
misters = df[df['Name'].str.contains("Mr.")]

# Select names that start with "A"
starts_with_a = df[df['Name'].str.startswith("A")]

In [ ]:
starts_with_a

In [ ]:
# Same as Method 2, but cleaner to read
rich_females = df.query('Sex == "female" and Pclass == 1')

In [ ]:
rich_females

In [ ]:
df.info()

In [ ]:
# Shows the count of missing values per column
df.isnull().sum()

In [ ]:
# Returns True if the column contains any nulls
df.isnull().any()

In [ ]:
# Counts how many rows are duplicates
df.duplicated()

In [ ]:
# Counts how many rows are duplicates
df.duplicated().sum()

In [ ]:
df[~df.duplicated(subset=["Pclass","Sex","Embarked"],keep = False)]

In [ ]:
df.query('Pclass == 2 and Embarked == "Q"')

In [ ]:
df[df["Embarked"]=="Q"].groupby("Pclass")["Pclass"].count()

In [ ]:
# Filters the DataFrame to show only the duplicated rows
df[df.duplicated(keep=False)]

In [ ]:
# Removes duplicate rows, keeping the first occurrence
df.drop_duplicates(subset=["Pclass","Sex","Embarked"],keep = False)

In [ ]:
# Shows the dtype of each column
df.dtypes

In [ ]:
# Converts the 'PassengerId' column to string (object)
s=df['Survived'].astype('str')

In [ ]:
s

In [ ]:
s[1]+s[2]

In [ ]:
# Shows the count of unique values per column
df.nunique()

In [ ]:
# Shows the counts for each unique value in the 'Embarked' column
df['Embarked'].value_counts()

In [ ]:
# Shows the counts for each unique value in the 'Sex' column
df['Sex'].value_counts()

In [ ]:
df.dtypes

In [ ]:
123//1.0

In [ ]:
df["Age_New"]=df['Age'].astype(dtype='int64',errors="ignore")

In [ ]:
df[df['Age']<10]

In [ ]:
df.astype?

In [ ]:
df['Ticket'].astype(str)

In [ ]:
pd.to_numeric(df['Ticket'],errors='coerce')

In [ ]:
pd.to_numeric?

In [ ]:
# Convert 'Age' column to integer (int64)
df['Age'].astype('int64')

# Convert 'Sex' column to the more memory-efficient 'category' type
df['Sex'].astype('category')

# Convert a numerical column to string
df['Ticket'].astype(str)

In [ ]:
# Example: Convert 'Fare' which might contain placeholder strings
df['Fare'] = pd.to_numeric(df['Fare'], errors='coerce')

# Now, any non-convertible strings in 'Fare' are set to NaN.
# You can then use df.fillna() or df.drop_na() to handle them.

In [ ]:
# Convert a standard date string column
df['Date'] = pd.to_datetime(df['DateString'])

In [ ]:
Code,  Meaning,          Example
%Y,    Year with century,2025
%m,    Month as a number,12
%d,    Day of the month,  15
%b,    Abbreviated month name,Dec

In [ ]:
# Example for a date string like '15-12-2025'
df['PurchaseDate'] = pd.to_datetime(
    df['PurchaseDate'], 
    format='%d-%m-%Y'
)

In [ ]:
# Extracts the word after the comma and before the period
df['Title'] = df['Name'].str.extract('([A-Za-z]+)\.')

In [ ]:
Attribute,Purpose,Example
.dt.year,Extracts the year as an integer.,df['Date'].dt.year
.dt.month,Extracts the month (1-12).,df['Date'].dt.month
.dt.day,Extracts the day of the month.,df['Date'].dt.day
.dt.day_name(),"Extracts the weekday name (e.g., 'Monday').",df['Date'].dt.day_name()
.dt.is_leap_year,Returns a boolean (True/False).,df['Date'].dt.is_leap_year

In [ ]:
# Extracts the week of the year (01-52)
df['Week_of_Year'] = df['OrderDate'].dt.isocalendar().week

# Filters for data in the first quarter (Jan, Feb, Mar)
q1_data = df[df['OrderDate'].dt.quarter == 1]

In [ ]:
# Convert to 'category' type first
df['Severity'] = df['Severity'].astype('category')

# Define the logical order
new_order = ['Low', 'Medium', 'High', 'Critical']

# Apply the new order
df['Severity'] = df['Severity'].cat.reorder_categories(new_order, ordered=True)

In [ ]:
# Calculate the average Fare paid by passengers in each Pclass (1st, 2nd, 3rd)
df.groupby('Pclass')['Fare'].mean()

In [ ]:
# Group by 'Pclass' and calculate:
# 1. The min and max of 'Age'
# 2. The sum of 'Fare'
grouped_stats = df.groupby('Pclass').agg(
    {
        'Age': ['min', 'max'],
        'Fare': 'sum'
    }
)

In [ ]:
grouped_stats

In [ ]:
df['Pclass'].value_counts().sort_index()

In [ ]:
df.isna().sum()

In [ ]:
df.isnull().sum()

In [ ]:
df[df['Embarked'].isna()]

In [ ]:
df['Embarked'].unique()

In [ ]:
df.dropna(how="any",axis=1)

In [ ]:
df['Embarked_fill']=df['Embarked'].fillna("Data Missing")

In [ ]:
df

In [ ]:
df['Embarked'].unique()

In [ ]:
df['Embarked_fill'].unique()

In [ ]:
df[df['Embarked'].isnull()]

In [ ]:
embares=df.loc[[60,61,62,63,64,65,828,829,830,831,832],:]

In [ ]:
embares['Embarked'].fillna(method='ffill')

In [ ]:
embares['Embarked'].fillna(method='bfill')

In [ ]:
df['Embarked'].mode()

In [ ]:
df['Embarked'].fillna("S").unique()

In [ ]:
# Filters the DataFrame to show only rows where 'Age' is null
missing_age_rows = df[df['Age'].isnull()]

In [ ]:
# Fills all missing 'Cabin' values with the string 'Unknown'
df['Cabin'].fillna('Unknown', inplace=True)

In [ ]:
# Calculate the median of the 'Age' column
age_median = df['Age'].median()

# Fill the missing 'Age' values with the calculated median
df['Age'].fillna(age_median, inplace=True)

Method,Description,Example
method='ffill',Forward Fill: Replaces null with the previous non-null value.,"df['StockPrice'].fillna(method='ffill', inplace=True)"
method='bfill',Backward Fill: Replaces null with the next non-null value.,"df['StockPrice'].fillna(method='bfill', inplace=True)"