# Complete Pandas Tutorial

Pandas is the most popular Python library for data manipulation and analysis. It provides two primary data structures:
- **Series**: 1D labeled array
- **DataFrame**: 2D labeled data structure (like a spreadsheet)

This tutorial covers everything from basics to advanced operations like merging, grouping, handling missing data, and visualization.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Set display options
pd.set_option('display.max_columns', None)
np.random.seed(42)

## 1. Series – One-Dimensional Labeled Array

In [ ]:
s1 = pd.Series([1, 2, 3, 4, 5])
print("Default index:")
print(s1)

In [ ]:
s1[0]

In [ ]:
s2 = pd.Series([1, 2, 3, 4], index=['A', 'B', 'C', 'D'])
print("\nCustom index:")
print(s2)

In [ ]:
s2.at['A']

In [ ]:
s2.iat[0]

In [ ]:
s3 = pd.Series({'a': 10, 'b': 20, 'c': 30})
print("\nFrom dict:")
print(s3)

In [ ]:
# From list
s1 = pd.Series([1, 2, 3, 4, 5])
print("Default index:")
print(s1)

# With custom index
s2 = pd.Series([1, 2, 3, 4], index=['A', 'B', 'C', 'D'])
print("\nCustom index:")
print(s2)

# From dictionary (keys become index)
s3 = pd.Series({'a': 10, 'b': 20, 'c': 30})
print("\nFrom dict:")
print(s3)

In [ ]:
s2.iloc[1:3]

In [ ]:
s2.loc['B':'C']

In [ ]:
s2

In [ ]:
s2[1:3]

In [ ]:
s2['B':'C']

In [ ]:
s2

In [ ]:
s2+10

In [ ]:
s2.mean()

In [ ]:
s2.max()

In [ ]:
s2.min()

In [ ]:
s2.sum()

In [ ]:
len(s2)

In [ ]:
type(s2)

In [ ]:
s2>3

In [ ]:
s2[s2>3]

In [ ]:
s2.where(s2%2==0,'Odd')

In [ ]:
# Accessing elements
print("By integer position:", s2.iat[0])        # 1
print("By label:", s2['B'])                # 2
print("Slicing by label (includes end):", s2['B':'D'])  # B 2, C 3, D 4
print("Slicing by position (excludes end):", s2[1:3])   # B 2, C 3

# Vectorized operations
print("s2 + 10:\n", s2 + 10)
print("s2.mean():", s2.mean())
print("s2 > 2:\n", s2 > 2)

## 2. DataFrame – Two-Dimensional Table

### Creating DataFrames

In [ ]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'London', 'Paris', 'Tokyo']
},index = ['A','B','C','D'])
print("DataFrame from dict:\n", df)

In [ ]:
df = pd.DataFrame({
    'Name': ('Alice', 'Bob', 'Charlie', 'Diana','Shubham'),
    'Age': (25, 30, 35, 28,np.nan),
    'City': ('New York', 'London', 'Paris', 'Tokyo',np.nan)
},index = ['A','B','C','D','E'])
print("DataFrame from dict:\n", df)

In [ ]:
data = [
    {'Name': 'Alice', 'Age': 25, 'City': 'New York'},
    {'Name': 'Bob', 'Age': 30, 'City': 'London'}
]
df2 = pd.DataFrame(data)
print("\nFrom list of dicts:\n", df2)

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
df3 = pd.DataFrame(arr, index = ['Row1','Row2'],columns=['A', 'B', 'C'])
print("\nFrom NumPy array:\n", df3)

In [ ]:
type(df3)

In [ ]:
# From dictionary of lists
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'London', 'Paris', 'Tokyo']
},index = ['A','B','C','D'])
print("DataFrame from dict:\n", df)

# From list of dictionaries
data = [
    {'Name': 'Alice', 'Age': 25, 'City': 'New York'},
    {'Name': 'Bob', 'Age': 30, 'City': 'London'}
]
df2 = pd.DataFrame(data)
print("\nFrom list of dicts:\n", df2)

# From NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6]])
df3 = pd.DataFrame(arr, index = ['Row1','Row2'],columns=['A', 'B', 'C'])
print("\nFrom NumPy array:\n", df3)

### DataFrame Attributes

In [ ]:
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print("Index:", df.index.tolist())
print("Data types:\n", df.dtypes)
print("\nInfo:")
df.info()

In [ ]:
type(df)

### Previewing Data

In [2]:
titanic = pd.read_excel('Titanic.xlsx')

In [ ]:
titanic

In [ ]:
titanic.to_json('Titanic_demo.json',index = False)

In [ ]:
titanic.to_csv('Titanic_demo.csv',index = False)

In [ ]:
score = pd.read_json(r"C:\Users\SHUBHAM\Desktop\RockPaperScissor\score.json")

In [ ]:
score

In [ ]:
record = pd.read_csv(r"C:\Users\SHUBHAM\Desktop\B07_Python\demo.txt")

In [ ]:
record

In [ ]:
record['age'] = 20

In [ ]:
record

In [ ]:
record.to_csv(r"C:\Users\SHUBHAM\Desktop\RockPaperScissor\demo.csv",index = 0)

In [ ]:
demo = pd.read_csv(r"C:\Users\SHUBHAM\Desktop\RockPaperScissor\demo.csv")

In [ ]:
demo

In [ ]:
demo.to_excel(r"C:\Users\SHUBHAM\Desktop\RockPaperScissor\demo.xlsx",index=False) # xlrd,openpyxl

In [ ]:
titanic = pd.read_excel("Titanic.xlsx")

In [ ]:
titanic

In [ ]:
titanic.info()

In [ ]:
titanic.nunique()

In [ ]:
titanic['Survived'].nunique()

In [ ]:
titanic['Survived'].unique()

In [ ]:
titanic.columns.to_list()

In [ ]:
titanic.index.to_list()

In [ ]:
titanic['Pclass'].unique()

In [ ]:
titanic['Sex'].unique()

In [ ]:
titanic['Embarked'].unique()

In [ ]:
titanic.unique()

In [ ]:
titanic.head(10)

In [ ]:
titanic.tail(10)

In [ ]:
titanic.sample(10)

In [ ]:
titanic.describe()

In [ ]:
titanic.columns

In [ ]:
titanic['Name']

In [ ]:
titanic[['Name']]

In [ ]:
titanic[[ 'Pclass','Survived', 'Name', 'Sex', 'Age']]

In [ ]:
titanic.loc[0,'Name']

In [ ]:
titanic.at[0,'Name']

In [ ]:
titanic.info()

In [ ]:
titanic.iat[0,3]

In [ ]:
titanic.iloc[0,3]

In [ ]:
titanic.iloc[:25,3:5]

In [ ]:
titanic.iloc[:,3]

In [ ]:
titanic.iloc[:,[3,1,2,5]]

In [ ]:
titanic.iloc[:,3:]

In [ ]:
type(titanic['Name'])

In [ ]:
type(titanic[['Name']])

In [ ]:
titanic['Name']

In [ ]:
titanic[['Name']]

In [ ]:
# Using sample dataset (Titanic from seaborn or built-in)
titanic = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
print("Head (first 5 rows):")
print(titanic.head())
print("\nTail (last 5 rows):")
print(titanic.tail())
print("\nRandom sample (3 rows):")
print(titanic.sample(3))
print("\nShape:", titanic.shape)

In [ ]:
titanic.isnull().sum()

In [ ]:
titanic.isnull().mean()*100

In [ ]:
titanic.isnull().sum()

In [ ]:
titanic.dropna()

In [ ]:
titanic[titanic.isna().any(axis=1)]

In [ ]:
titanic.head()

In [ ]:
titanic.tail()

In [ ]:
titanic.head(10)

In [ ]:
titanic.tail(10)

In [ ]:
titanic.sample()

In [ ]:
titanic.sample(5)

## 3. Indexing and Selection

- `df[column]` – select a column (returns Series)
- `df[[col1, col2]]` – select multiple columns (returns DataFrame)
- `df.loc[row_label, column_label]` – label-based indexing
- `df.iloc[row_position, column_position]` – integer position-based
- `df.at[row_label, col_label]` – fast scalar access
- `df.iat[row_pos, col_pos]` – fast integer scalar access

In [ ]:
titanic.columns.to_list()

In [ ]:
titanic['Name']

In [ ]:
titanic[['Name']]

In [ ]:
titanic[['Name','Age']]

In [ ]:
titanic.info()

In [ ]:
titanic[['Age',"Name"]]

In [ ]:
titanic[[0,1]]

In [ ]:
titanic.head()

In [ ]:
titanic.at[0,'Name']

In [ ]:
titanic.at[0,"Age"]

In [ ]:
titanic.iat[0,1]

In [ ]:
titanic.loc[0,:]

In [ ]:
titanic.loc[0:4,:]

In [ ]:
titanic.iloc[0:5,:]

In [ ]:
titanic.loc[[1,0,3,4,2],:]

In [ ]:
# Column selection
print("Single column (Series):\n", titanic['Name'].head(2))
print("\nMultiple columns (DataFrame):\n", titanic[['Name', 'Age']].head(2))

# Row selection with .loc
print("\nRow 0 with .loc:")
print(titanic.loc[0])
print("\nRows 0-2, columns 'Name' and 'Age' with .loc:")
print(titanic.loc[0:2, ['Name', 'Age']])   # label slice includes end

# Row selection with .iloc
print("\nFirst row with .iloc:")
print(titanic.iloc[0])
print("\nRows 0-2 (excludes 3), columns 2-4 with .iloc:")
print(titanic.iloc[0:3, 2:5])

# Fast scalar access
print("\n.at[0, 'Name']:", titanic.at[0, 'Name'])
print(".iat[0, 2]:", titanic.iat[0, 2])

## 4. Boolean Indexing (Filtering)

In [ ]:
titanic['Age'] > 30

In [ ]:
titanic[titanic['Age'] > 30]

In [ ]:
titanic['Embarked'] == 'S'

In [ ]:
titanic[(titanic['Age'] > 30) & (titanic['Embarked'] == 'S') & (titanic['Sex'] == 'female') & (titanic['Pclass'] >1)].shape[0]

In [ ]:
adults = titanic[titanic['Age'] > 30]
print(f"Number of passengers older than 30: {len(adults),adults.shape[0]}")

In [ ]:
titanic.shape[1]

In [ ]:
(titanic['Age']>70).sum()

In [ ]:
data = np.where(titanic['Age']<10,'Child','Not Child')

In [ ]:
data

In [ ]:
titanic.insert(6,"IsChild",data)

In [ ]:
titanic.query("IsChild=='Child'")

In [ ]:
titanic

In [ ]:
titanic.query("Age>70 and Survived == 1")

In [ ]:
titanic[titanic['Age']>70]

In [ ]:
titanic[(titanic['Pclass'] == 1) & ~(titanic['Sex'] == 'female')]

In [ ]:
titanic[(titanic['Pclass'] == 1) | ~(titanic['Sex'] == 'female')]

In [ ]:
titanic[(titanic['Pclass'] == 1) | (titanic['Sex'] == 'female')]

In [ ]:
titanic[(titanic['Pclass'] == 1) & (titanic['Sex'] == 'female')]

In [ ]:
titanic[titanic['Pclass'] == 1]

In [ ]:
# Single condition
adults = titanic[titanic['Age'] > 30]
print(f"Number of passengers older than 30: {len(adults)}")

# Multiple conditions (& for AND, | for OR, ~ for NOT)
rich_females = titanic[(titanic['Sex'] == 'female') & (titanic['Pclass'] == 1)]
print(f"\nFirst class females: {len(rich_females)}")
print(rich_females[['Name', 'Age', 'Fare']].head())

# Using .isin()
southampton = titanic[titanic['Embarked'].isin(['S', 'C'])]
print(f"\nPassengers from Southampton or Cherbourg: {len(southampton)}")

# Using .query() (alternative syntax)
young_males = titanic.query('Age < 18 and Sex == "male"')
print(f"\nYoung males: {len(young_males)}")

## 5. Sorting

In [ ]:
titanic.sort_values('Age', ascending=True)

In [ ]:
titanic.sort_values?

In [ ]:
x = titanic.sort_values(by = ['Age','Name'],ascending=[True,True])

In [ ]:
X = x.sort_index(axis=1,ascending =False)

In [ ]:
x

In [ ]:
X.sort_index(axis = 0,ascending = False)

In [ ]:
# Sort by single column
by_age = titanic.sort_values('Age', ascending=False)
print("Oldest passengers:")
print(by_age[['Name', 'Age']].head())

# Sort by multiple columns
by_class_age = titanic.sort_values(['Pclass', 'Age'], ascending=[True, False])
print("\nSort by Pclass (ascending), then Age (descending):")
print(by_class_age[['Pclass', 'Name', 'Age']].head())

# Sort by index
titanic_sorted_index = titanic.sort_index(ascending=False)
print("\nIndex sorted descending:", titanic_sorted_index.index[:5].tolist())

## 6. Handling Missing Data

In [ ]:
titanic[titanic['Embarked'].isnull()]

In [ ]:
titanic.isnull().mean()*100

In [ ]:
titanic.isnull().sum()

In [ ]:
titanic['Embarked'].isnull()

In [ ]:
titanic['Age'].mean()

In [ ]:
titanic['Age'].median()

In [ ]:
titanic

In [ ]:
fill_df  = titanic.fillna({'Age':titanic['Age'].mean()})

In [ ]:
fill_df.fillna?

In [ ]:
fill_df = fill_df.fillna({'Embarked':'S'})

In [ ]:
fill_df.isnull().sum()

In [ ]:
fill_df.drop('Cabin',axis=1)

In [ ]:
fill_df.drop(columns = ['Cabin'],inplace=True)

In [ ]:
fill_df.isna().sum()

In [ ]:
titanic['Embarked'].mode()

In [ ]:
titanic.fillna({'Embarked':}

In [ ]:
titanic['Age'].fillna(titanic['Age'].mean()).isna().sum()

In [ ]:
titanic[titanic['Embarked'].isnull()]

In [ ]:
titanic['Embarked'].unique()

In [ ]:
titanic['Embarked'].value_counts()

In [ ]:
titanic.isna()

In [ ]:
titanic[titanic.isnull().any(axis=1)]

In [ ]:
x = np.arange(891)

In [ ]:
titanic.insert(0,'X',x)

In [ ]:
titanic

In [ ]:
titanic.insert?

In [ ]:
titanic.insert(0,"Demo",np.nan)

In [ ]:
titanic.dropna(how ='all',axis = 1,inplace = True)

In [ ]:
titanic.rename({'X':'Ser'},axis =1)

In [ ]:
titanic.dropna(how = 'any',axis=1)

In [4]:
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
print("Missing values per column:")
print(titanic.isnull().sum())
print("\nPercentage missing:")
print(titanic.isnull().mean() * 100)

Missing values per column:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Percentage missing:
PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

In [7]:
titanic.dropna?

Signature:
titanic.dropna(
    *,
    axis: 'Axis' = 0,
    how: 'AnyAll | lib.NoDefault' = <no_default>,
    thresh: 'int | lib.NoDefault' = <no_default>,
    subset: 'IndexLabel | AnyArrayLike | None' = None,
    inplace: 'bool' = False,
    ignore_index: 'bool' = False,
) -> 'DataFrame | None'
Docstring:
Remove missing values.

See the :ref:`User Guide <missing_data>` for more on which values are
considered missing, and how to work with missing data.

Parameters
----------
axis : {0 or 'index', 1 or 'columns'}, default 0
    Determine if rows or columns which contain missing values are
    removed.

    * 0, or 'index' : Drop rows which contain missing values.
    * 1, or 'columns' : Drop columns which contain missing value.

    Only a single axis is allowed.

how : {'any', 'all'}, default 'any'
    Determine if row or column is removed from DataFrame, when we have
    at least one NA or all NA.

    * 'any' : If any NA values are present, drop that row or column.
    * 'all' : If all values are NA, drop that row or column.

thresh : int, optional
    Require that many non-NA values. Cannot be combined with how.
subset : column label or iterable of labels, optional
    Labels along other axis to consider, e.g. if you are dropping rows
    these would be a list of columns to include.
inplace : bool, default False
    Whether to modify the DataFrame rather than creating a new one.
ignore_index : bool, default ``False``
    If ``True``, the resulting axis will be labeled 0, 1, …, n - 1.

    .. versionadded:: 2.0.0

Returns
-------
DataFrame or None
    DataFrame with NA entries dropped from it or None if ``inplace=True``.

See Also
--------
DataFrame.isna: Indicate missing values.
DataFrame.notna : Indicate existing (non-missing) values.
DataFrame.fillna : Replace missing values.
Series.dropna : Drop missing values.
Index.dropna : Drop missing indices.

Examples
--------
>>> df = pd.DataFrame(
...     {
...         "name": ["Alfred", "Batman", "Catwoman"],
...         "toy": [np.nan, "Batmobile", "Bullwhip"],
...         "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT],
...     }
... )
>>> df
       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

Drop the rows where at least one element is missing.

>>> df.dropna()
     name        toy       born
1  Batman  Batmobile 1940-04-25

Drop the columns where at least one element is missing.

>>> df.dropna(axis="columns")
       name
0    Alfred
1    Batman
2  Catwoman

Drop the rows where all elements are missing.

>>> df.dropna(how="all")
       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

Keep only the rows with at least 2 non-NA values.

>>> df.dropna(thresh=2)
       name        toy       born
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

Define in which columns to look for missing values.

>>> df.dropna(subset=["name", "toy"])
       name        toy       born
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT
File:      c:\users\shubham\appdata\local\programs\python\python312\lib\site-packages\pandas\core\frame.py
Type:      method

In [11]:
titanic.dropna(how = 'all',axis = 0)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [20]:
sample_row = [[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]]
for i in range(12):
    sample_row.append(np.nan)

NameError: name 'nan' is not defined

In [14]:
sample_row

[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]

In [17]:
df = pd.concat((titanic,pd.DataFrame(sample_row)),axis=1)

In [18]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,0
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,NaN
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,NaN
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,NaN
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,NaN
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,NaN
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,NaN
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,NaN

In [23]:
df1 = df.iloc[:,:8]

In [24]:
df2 = df.iloc[:,8:]

In [25]:
df1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0
...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0

In [26]:
df2

               Ticket     Fare Cabin Embarked   0
0           A/5 21171   7.2500   NaN        S NaN
1            PC 17599  71.2833   C85        C NaN
2    STON/O2. 3101282   7.9250   NaN        S NaN
3              113803  53.1000  C123        S NaN
4              373450   8.0500   NaN        S NaN
..                ...      ...   ...      ...  ..
886            211536  13.0000   NaN        S NaN
887            112053  30.0000   B42        S NaN
888        W./C. 6607  23.4500   NaN        S NaN
889            111369  30.0000  C148        C NaN
890            370376   7.7500   NaN        Q NaN

[891 rows x 5 columns]

In [28]:
pd.concat((df1,df2),axis = 1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,0
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,NaN
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,NaN
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,NaN
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,NaN
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,NaN
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,NaN
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,NaN

In [19]:
df.dropna(how = "all",axis = 1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [30]:
df3 = df.iloc[:500,:]

In [31]:
df4 = df.iloc[500:,:]

In [32]:
df3

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,0
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,NaN
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,NaN
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,NaN
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,0,3,"Yousseff, Mr. Gerious",male,NaN,0,0,2627,14.4583,NaN,C,NaN
496,497,1,1,"Eustis, Miss Elizabeth Mussey",female,54.0,1,0,36947,78.2667,D20,C,NaN
497,498,0,3,"Shellard, Mr. Frederick William",male,NaN,0,0,C.A. 6212,15.1000,NaN,S,NaN
498,499,0,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.5500,C22 C26,S,NaN
499,500,0,3,"Svensson, Mr. Olof",male,24.0,0,0,350035,7.7958,NaN,S,NaN

In [33]:
df4

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,0
500,501,0,3,"Calic, Mr. Petar",male,17.0,0,0,315086,8.6625,NaN,S,NaN
501,502,0,3,"Canavan, Miss Mary",female,21.0,0,0,364846,7.7500,NaN,Q,NaN
502,503,0,3,"O'Sullivan, Miss Bridget Mary",female,NaN,0,0,330909,7.6292,NaN,Q,NaN
503,504,0,3,"Laitinen, Miss Kristina Sofia",female,37.0,0,0,4135,9.5875,NaN,S,NaN
504,505,1,1,"Maioni, Miss Roberta",female,16.0,0,0,110152,86.5000,B79,S,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,NaN
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,NaN
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,NaN
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,NaN

In [34]:
pd.concat((df3,df4))

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,0
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,NaN
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,NaN
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,NaN
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,NaN
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,NaN
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,NaN
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,NaN

In [42]:
titanic.bfill().isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          1
Embarked       0
dtype: int64

In [49]:
titanic.duplicated?

Signature:
titanic.duplicated(
    subset: 'Hashable | Iterable[Hashable] | None' = None,
    keep: 'DropKeep' = 'first',
) -> 'Series'
Docstring:
Return boolean Series denoting duplicate rows.

Considering certain columns is optional.

Parameters
----------
subset : column label or iterable of labels, optional
    Only consider certain columns for identifying duplicates, by
    default use all of the columns.
keep : {'first', 'last', False}, default 'first'
    Determines which duplicates (if any) to mark.

    - ``first`` : Mark duplicates as ``True`` except for the first occurrence.
    - ``last`` : Mark duplicates as ``True`` except for the last occurrence.
    - False : Mark all duplicates as ``True``.

Returns
-------
Series
    Boolean series for each duplicated rows.

See Also
--------
Index.duplicated : Equivalent method on index.
Series.duplicated : Equivalent method on Series.
Series.drop_duplicates : Remove duplicate values from Series.
DataFrame.drop_duplicates : Remove duplicate values from DataFrame.

Examples
--------
Consider dataset containing ramen rating.

>>> df = pd.DataFrame(
...     {
...         "brand": ["Yum Yum", "Yum Yum", "Indomie", "Indomie", "Indomie"],
...         "style": ["cup", "cup", "cup", "pack", "pack"],
...         "rating": [4, 4, 3.5, 15, 5],
...     }
... )
>>> df
    brand style  rating
0  Yum Yum   cup     4.0
1  Yum Yum   cup     4.0
2  Indomie   cup     3.5
3  Indomie  pack    15.0
4  Indomie  pack     5.0

By default, for each set of duplicated values, the first occurrence
is set on False and all others on True.

>>> df.duplicated()
0    False
1     True
2    False
3    False
4    False
dtype: bool

By using 'last', the last occurrence of each set of duplicated values
is set on False and all others on True.

>>> df.duplicated(keep="last")
0     True
1    False
2    False
3    False
4    False
dtype: bool

By setting ``keep`` on False, all duplicates are True.

>>> df.duplicated(keep=False)
0     True
1     True
2    False
3    False
4    False
dtype: bool

To find duplicates on specific column(s), use ``subset``.

>>> df.duplicated(subset=["brand"])
0    False
1     True
2    False
3     True
4     True
dtype: bool
File:      c:\users\shubham\appdata\local\programs\python\python312\lib\site-packages\pandas\core\frame.py
Type:      method

In [47]:
duplicate = pd.concat((titanic,titanic))

In [48]:
duplicate.duplicated().sum()

891

In [59]:
duplicate = duplicate.set_index('PassengerId')

In [62]:
duplicate = duplicate.drop(columns = ['index'])

In [65]:
duplicate = duplicate.drop_duplicates()

In [66]:
duplicate

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [70]:
duplicate.rename?

Signature:
duplicate.rename(
    mapper: 'Renamer | None' = None,
    *,
    index: 'Renamer | None' = None,
    columns: 'Renamer | None' = None,
    axis: 'Axis | None' = None,
    copy: 'bool | lib.NoDefault' = <no_default>,
    inplace: 'bool' = False,
    level: 'Level | None' = None,
    errors: 'IgnoreRaise' = 'ignore',
) -> 'DataFrame | None'
Docstring:
Rename columns or index labels.

Function / dict values must be unique (1-to-1). Labels not contained in
a dict / Series will be left as-is. Extra labels listed don't throw an
error.

See the :ref:`user guide <basics.rename>` for more.

Parameters
----------
mapper : dict-like or function
    Dict-like or function transformations to apply to
    that axis' values. Use either ``mapper`` and ``axis`` to
    specify the axis to target with ``mapper``, or ``index`` and
    ``columns``.
index : dict-like or function
    Alternative to specifying axis (``mapper, axis=0``
    is equivalent to ``index=mapper``).
columns : dict-like or function
    Alternative to specifying axis (``mapper, axis=1``
    is equivalent to ``columns=mapper``).
axis : {0 or 'index', 1 or 'columns'}, default 0
    Axis to target with ``mapper``. Can be either the axis name
    ('index', 'columns') or number (0, 1). The default is 'index'.
copy : bool, default False
    This keyword is now ignored; changing its value will have no
    impact on the method.

    .. deprecated:: 3.0.0

        This keyword is ignored and will be removed in pandas 4.0. Since
        pandas 3.0, this method always returns a new object using a lazy
        copy mechanism that defers copies until necessary
        (Copy-on-Write). See the `user guide on Copy-on-Write
        <https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html>`__
        for more details.

inplace : bool, default False
    Whether to modify the DataFrame rather than creating a new one.
    If True then value of copy is ignored.
level : int or level name, default None
    In case of a MultiIndex, only rename labels in the specified
    level.
errors : {'ignore', 'raise'}, default 'ignore'
    If 'raise', raise a `KeyError` when a dict-like `mapper`, `index`,
    or `columns` contains labels that are not present in the Index
    being transformed.
    If 'ignore', existing keys will be renamed and extra keys will be
    ignored.

Returns
-------
DataFrame or None
    DataFrame with the renamed axis labels or None if ``inplace=True``.

Raises
------
KeyError
    If any of the labels is not found in the selected axis and
    "errors='raise'".

See Also
--------
DataFrame.rename_axis : Set the name of the axis.

Examples
--------
``DataFrame.rename`` supports two calling conventions

* ``(index=index_mapper, columns=columns_mapper, ...)``
* ``(mapper, axis={'index', 'columns'}, ...)``

We *highly* recommend using keyword arguments to clarify your
intent.

Rename columns using a mapping:

>>> df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
>>> df.rename(columns={"A": "a", "B": "c"})
   a  c
0  1  4
1  2  5
2  3  6

Rename index using a mapping:

>>> df.rename(index={0: "x", 1: "y", 2: "z"})
   A  B
x  1  4
y  2  5
z  3  6

Cast index labels to a different type:

>>> df.index
RangeIndex(start=0, stop=3, step=1)
>>> df.rename(index=str).index
Index(['0', '1', '2'], dtype='str')

>>> df.rename(columns={"A": "a", "B": "b", "C": "c"}, errors="raise")
Traceback (most recent call last):
KeyError: ['C'] not found in axis

Using axis-style parameters:

>>> df.rename(str.lower, axis="columns")
   a  b
0  1  4
1  2  5
2  3  6

>>> df.rename({1: 2, 2: 4}, axis="index")
   A  B
0  1  4
2  2  5
4  3  6
File:      c:\users\shubham\appdata\local\programs\python\python312\lib\site-packages\pandas\core\frame.py
Type:      method

In [71]:
duplicate.rename({'Sex':'Gender'},axis =1)

,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [69]:
duplicate[duplicate.duplicated(subset=['Sex','Age'])]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
15,0,3,"Vestrom, Miss Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
17,0,3,"Rice, Master Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [57]:
duplicate.drop_duplicates(keep = 'first')

,index,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [45]:
titanic.duplicated?

Signature:
titanic.duplicated(
    subset: 'Hashable | Iterable[Hashable] | None' = None,
    keep: 'DropKeep' = 'first',
) -> 'Series'
Docstring:
Return boolean Series denoting duplicate rows.

Considering certain columns is optional.

Parameters
----------
subset : column label or iterable of labels, optional
    Only consider certain columns for identifying duplicates, by
    default use all of the columns.
keep : {'first', 'last', False}, default 'first'
    Determines which duplicates (if any) to mark.

    - ``first`` : Mark duplicates as ``True`` except for the first occurrence.
    - ``last`` : Mark duplicates as ``True`` except for the last occurrence.
    - False : Mark all duplicates as ``True``.

Returns
-------
Series
    Boolean series for each duplicated rows.

See Also
--------
Index.duplicated : Equivalent method on index.
Series.duplicated : Equivalent method on Series.
Series.drop_duplicates : Remove duplicate values from Series.
DataFrame.drop_duplicates : Remove duplicate values from DataFrame.

Examples
--------
Consider dataset containing ramen rating.

>>> df = pd.DataFrame(
...     {
...         "brand": ["Yum Yum", "Yum Yum", "Indomie", "Indomie", "Indomie"],
...         "style": ["cup", "cup", "cup", "pack", "pack"],
...         "rating": [4, 4, 3.5, 15, 5],
...     }
... )
>>> df
    brand style  rating
0  Yum Yum   cup     4.0
1  Yum Yum   cup     4.0
2  Indomie   cup     3.5
3  Indomie  pack    15.0
4  Indomie  pack     5.0

By default, for each set of duplicated values, the first occurrence
is set on False and all others on True.

>>> df.duplicated()
0    False
1     True
2    False
3    False
4    False
dtype: bool

By using 'last', the last occurrence of each set of duplicated values
is set on False and all others on True.

>>> df.duplicated(keep="last")
0     True
1    False
2    False
3    False
4    False
dtype: bool

By setting ``keep`` on False, all duplicates are True.

>>> df.duplicated(keep=False)
0     True
1     True
2    False
3    False
4    False
dtype: bool

To find duplicates on specific column(s), use ``subset``.

>>> df.duplicated(subset=["brand"])
0    False
1     True
2    False
3     True
4     True
dtype: bool
File:      c:\users\shubham\appdata\local\programs\python\python312\lib\site-packages\pandas\core\frame.py
Type:      method

In [12]:
titanic.insert?

Signature:
titanic.insert(
    loc: 'int',
    column: 'Hashable',
    value: 'object',
    allow_duplicates: 'bool | lib.NoDefault' = <no_default>,
) -> 'None'
Docstring:
Insert column into DataFrame at specified location.

Raises a ValueError if `column` is already contained in the DataFrame,
unless `allow_duplicates` is set to True.

Parameters
----------
loc : int
    Insertion index. Must verify 0 <= loc <= len(columns).
column : str, number, or hashable object
    Label of the inserted column.
value : Scalar, Series, or array-like
    Content of the inserted column.
allow_duplicates : bool, optional, default lib.no_default
    Allow duplicate column labels to be created.

See Also
--------
Index.insert : Insert new item by index.

Examples
--------
>>> df = pd.DataFrame({"col1": [1, 2], "col2": [3, 4]})
>>> df
   col1  col2
0     1     3
1     2     4
>>> df.insert(1, "newcol", [99, 99])
>>> df
   col1  newcol  col2
0     1      99     3
1     2      99     4
>>> df.insert(0, "col1", [100, 100], allow_duplicates=True)
>>> df
   col1  col1  newcol  col2
0   100     1      99     3
1   100     2      99     4

Notice that pandas uses index alignment in case of `value` from type `Series`:

>>> df.insert(0, "col0", pd.Series([5, 6], index=[1, 2]))
>>> df
   col0  col1  col1  newcol  col2
0   NaN   100     1      99     3
1   5.0   100     2      99     4
File:      c:\users\shubham\appdata\local\programs\python\python312\lib\site-packages\pandas\core\frame.py
Type:      method

In [ ]:
# Detect missing values
print("Missing values per column:")
print(titanic.isnull().sum())
print("\nPercentage missing:")
print(titanic.isnull().mean() * 100)

# Drop rows with any missing values
titanic_dropped_rows = titanic.dropna()
print(f"\nShape after dropna(): {titanic_dropped_rows.shape}")

# Drop columns with any missing values
titanic_dropped_cols = titanic.dropna(axis=1)
print(f"Shape after dropna(axis=1): {titanic_dropped_cols.shape}")
age_fill = titanic_filled['Age'].median()
print(age_fill)
embarked_fill = titanic_filled['Embarked'].mode()[0]
# Fill missing values
titanic_filled = titanic.copy()
titanic_filled.fillna({'Age':age_fill,'Embarked':embarked_fill},inplace = True)
#titanic_filled['Embarked'].fillna(titanic_filled['Embarked'].mode()[0], inplace=True)
print(f"\nMissing Age after median fill: {titanic_filled['Age'].isnull().sum()}")

# Forward fill and backward fill
sample_series = pd.Series([1, 2, None, 4, None, 6])
print("\nOriginal:", sample_series.tolist())
print("Forward fill:", sample_series.fillna(method='ffill').tolist())
#print("Backward fill:", sample_series.fillna(method='bfill').tolist())
titanic_filled.isna().sum()

In [ ]:
titanic.ffill?

In [ ]:
titanic_filled.drop('Cabin',axis=1)

## 7. Data Type Conversion

In [ ]:
titanic.isna().sum()

In [ ]:
titanic.dtypes

In [ ]:
pd.to_numeric?

In [ ]:
# Check dtypes
print("Original dtypes:\n", titanic.dtypes)

# Convert to string
titanic['Survived_str'] = titanic['Survived'].astype(str)

# Convert to category (memory efficient)
titanic['Sex_cat'] = titanic['Sex'].astype('category')

# Convert to numeric (coerce errors)
titanic['Fare_numeric'] = pd.to_numeric(titanic['Fare'], errors='coerce')

# Convert to datetime
date_df = pd.DataFrame({'date_str': ['2024-01-15', '2024-02-20']})
date_df['date'] = pd.to_datetime(date_df['date_str'])
print("\nDatetime conversion:\n", date_df.dtypes)

In [ ]:
date_df = pd.DataFrame({'date_str': ['2024-15-january', '2024-20-february','123a']})

In [ ]:
date_df.dtypes

In [ ]:
pd.to_datetime?

In [ ]:
date_df['date'] = pd.to_datetime(date_df['date_str'],errors ='coerce',format='%Y-%d-%B')
print("\nDatetime conversion:\n", date_df.dtypes)

In [ ]:
date_df

In [ ]:
date_df['date'].dt.strftime('%y-%b-%a')

## 8. Aggregations (Summary Statistics)

In [ ]:
titanic.describe()

In [ ]:
titanic.query('Fare > 31').groupby('Sex')['Fare'].mean()

In [ ]:
titanic.query('Fare>512')

In [ ]:
titanic.query('Fare > 31').groupby('Sex')['Fare'].min()

In [ ]:
titanic['Sex'].unique()

In [ ]:
titanic['Pclass'].unique()

In [ ]:
titanic['Pclass'].nunique()

In [ ]:
titanic.nunique()

In [ ]:
titanic['Embarked'].unique()

In [ ]:
titanic.unique()

In [ ]:
# Basic statistics for numeric columns
print("describe():")
print(titanic.describe())

# Specific aggregates
print(f"\nMean Age: {titanic['Age'].mean():.2f}")
print(f"Median Fare: {titanic['Fare'].median():.2f}")
print(f"Max Age: {titanic['Age'].max():.2f}")
print(f"Min Age: {titanic['Age'].min()}")
print(f"Std Age: {titanic['Age'].std():.2f}")

# For categorical columns
print("\nValue counts for Embarked:")
print(titanic['Embarked'].value_counts())
print("\nUnique values in Sex:", titanic['Sex'].unique())
print("Number of unique tickets:", titanic['Ticket'].nunique())

## 9. GroupBy Operations

Split-Apply-Combine: split data into groups, apply a function, combine results.

In [ ]:
titanic.sort_index?

In [ ]:
titanic.groupby('Sex')['Survived'].value_counts().sort_index()

In [ ]:
titanic.groupby('Sex')['Survived'].mean()

In [ ]:
titanic.groupby(['Pclass'])['Sex'].value_counts()

In [ ]:
titanic.groupby(['Pclass', 'Sex'])['Survived'].value_counts()

In [ ]:
titanic.groupby(['Pclass', 'Sex'])['Survived'].mean()

In [ ]:
agg_result = titanic.groupby('Pclass').agg({
    'Age': ['mean', 'min', 'max'],
    'Fare': ['sum', 'mean']
})

In [ ]:
agg_result

In [ ]:
titanic.groupby('Sex').size()

In [ ]:
titanic.groupby('Embarked').size()

In [ ]:
titanic.groupby('Survived').size()

In [ ]:
titanic.groupby('Pclass').size()

In [ ]:
# Single column group
survival_by_sex = titanic.groupby('Sex')['Survived'].mean()
print("Survival rate by sex:")
print(survival_by_sex)

# Multiple columns group
survival_by_class_sex = titanic.groupby(['Pclass', 'Sex'])['Survived'].mean()
print("\nSurvival rate by class and sex:")
print(survival_by_class_sex)

# Multiple aggregations
agg_result = titanic.groupby('Pclass').agg({
    'Age': ['mean', 'min', 'max'],
    'Fare': ['sum', 'mean']
})
print("\nAggregations by Pclass:")
print(agg_result)

# Count per group
print("\nCount by Embarked:")
print(titanic.groupby('Embarked').size())

# Custom aggregation with .apply
def range_func(x):
    return x.max() - x.min()

age_range_by_class = titanic.groupby('Pclass')['Age'].apply(range_func)
print("\nAge range by class:")
print(age_range_by_class)

## 10. Merging and Concatenating DataFrames

- `pd.concat()` – stack DataFrames vertically (rows) or horizontally (columns)
- `pd.merge()` – join DataFrames on keys (like SQL joins)

In [ ]:
# Create sample data
df_left = pd.DataFrame({'key': ['A', 'B', 'C'], 'value_left': [1, 2, 3]})
df_right = pd.DataFrame({'key': ['B', 'C', 'D'], 'value_right': [4, 5, 6]})
print("Left DataFrame:\n", df_left)
print("\nRight DataFrame:\n", df_right)

In [ ]:
# Concatenate vertically (rows)
df_concat_rows = pd.concat([df_left, df_right], ignore_index=True)
print("\nConcatenated rows:\n", df_concat_rows)

In [ ]:
# Concatenate horizontally (columns)
df_concat_cols = pd.concat([df_left, df_right], axis=1)
print("\nConcatenated columns:\n", df_concat_cols)

In [ ]:
# Create sample data
df_left = pd.DataFrame({'key': ['A', 'B', 'C'], 'value_left': [1, 2, 3]})
df_right = pd.DataFrame({'key': ['B', 'C', 'D'], 'value_right': [4, 5, 6]})
print("Left DataFrame:\n", df_left)
print("\nRight DataFrame:\n", df_right)

# Concatenate vertically (rows)
df_concat_rows = pd.concat([df_left, df_right], ignore_index=True)
print("\nConcatenated rows:\n", df_concat_rows)

# Concatenate horizontally (columns)
df_concat_cols = pd.concat([df_left, df_right], axis=1)
print("\nConcatenated columns:\n", df_concat_cols)

In [ ]:
# Inner join (only keys present in both)
inner = pd.merge(df_left, df_right, on='key', how='inner')
print("Inner join:\n", inner)

In [ ]:
# Left join (all keys from left)
left = pd.merge(df_left, df_right, on='key', how='left')
print("\nLeft join:\n", left)

In [ ]:
# Right join (all keys from right)
right = pd.merge(df_left, df_right, on='key', how='right')
print("\nRight join:\n", right)

In [ ]:
# Outer join (union of keys)
outer = pd.merge(df_left, df_right, on='key', how='outer')
print("\nOuter join:\n", outer)

In [ ]:
# Cross join (Cartesian product)
cross = pd.merge(df_left, df_right, how='cross')
print("\nCross join:\n", cross)

In [ ]:
# Inner join (only keys present in both)
inner = pd.merge(df_left, df_right, on='key', how='inner')
print("Inner join:\n", inner)

# Left join (all keys from left)
left = pd.merge(df_left, df_right, on='key', how='left')
print("\nLeft join:\n", left)

# Right join (all keys from right)
right = pd.merge(df_left, df_right, on='key', how='right')
print("\nRight join:\n", right)

# Outer join (union of keys)
outer = pd.merge(df_left, df_right, on='key', how='outer')
print("\nOuter join:\n", outer)

# Cross join (Cartesian product)
cross = pd.merge(df_left, df_right, how='cross')
print("\nCross join:\n", cross)

## 11. Apply Functions (`apply`, `map`, `applymap`)

- `apply()` – apply function to rows or columns of DataFrame
- `map()` – apply function element-wise to Series
- `applymap()` – element-wise to DataFrame

In [ ]:
titanic.head()

In [ ]:
type(titanic['Age'].apply(lambda x:x+5))

In [ ]:
# Series.map (element-wise)
titanic['Sex_code'] = titanic['Sex'].map({'male': 0, 'female': 1})
print("Sex mapped to 0/1:")
print(titanic[['Sex', 'Sex_code']].head())
type(titanic['Sex_code'])

In [ ]:
def age_class(age):
    if age < 10:
        return 'Child'
    elif age >=10 and age <= 16:
        return 'Teenager'
    elif age >=17 and age <=25:
        return 'Young'
    elif age>= 26 and age <=40:
        return 'Adult'
    elif age>= 41 and age <=60:
        return 'Mid Adult'
    elif age>= 61 and age <=120:
        return 'Senior Citizen'
    elif pd.isna(age):
        return 'Unknown'

In [ ]:
titanic.drop('Age Code',axis=1,inplace =True)

In [ ]:
titanic.insert(6,'Age Code',titanic['Age'].map(age_class))

In [ ]:
titanic.rename({'Sex':'Gender'},axis = 1,inplace =True)

In [ ]:
titanic.groupby(['Age Code','Gender'])['Survived'].value_counts()

In [ ]:
titanic.query('Gender == "male" and Age >=17 and Age <= 25 and Survived == 1')

In [ ]:
titanic.columns

In [ ]:
titanic.query('Age>60 and Gender == "female"')

In [ ]:
titanic.head()

In [ ]:
# Series.map (element-wise)
titanic['Sex_code'] = titanic['Gender'].map({'male': 0, 'female': 1})
print("Sex mapped to 0/1:")
print(titanic[['Gender', 'Sex_code']].head())

# DataFrame.apply (row-wise or column-wise)
# Calculate age group
def age_group(age):
    if pd.isna(age):
        return 'Unknown'
    elif age < 18:
        return 'Child'
    elif age < 60:
        return 'Adult'
    else:
        return 'Senior'

titanic['AgeGroup'] = titanic['Age'].apply(age_group)
print("\nAge groups:")
print(titanic['AgeGroup'].value_counts())

# Apply to entire DataFrame (element-wise)
df_small = pd.DataFrame([[1, 2], [3, 4]], columns=['A', 'B'])
df_squared = df_small.applymap(lambda x: x**2)
print("\nElement-wise square with applymap:\n", df_squared)

## 12. Working with Dates and Times

In [ ]:
# Create datetime data
dates = pd.date_range('2024-01-01', periods=10, freq='D')
df_dates = pd.DataFrame({'date': dates, 'value': np.random.randn(10)})
print("DataFrame with dates:\n", df_dates.head())

# Extract date components
df_dates['year'] = df_dates['date'].dt.year
df_dates['month'] = df_dates['date'].dt.month
df_dates['day'] = df_dates['date'].dt.day
df_dates['weekday'] = df_dates['date'].dt.day_name()
print("\nExtracted components:\n", df_dates.head())

# Filter by date
jan_data = df_dates[df_dates['date'].dt.month == 1]
print(f"\nJanuary data: {len(jan_data)} rows")

# Set date as index and resample
df_dates.set_index('date', inplace=True)
weekly_mean = df_dates['value'].resample('W').mean()
print("\nWeekly average values:")
print(weekly_mean)

## 13. Handling Duplicates

In [ ]:
titanic.duplicated().sum()

In [ ]:
titanic[~titanic.duplicated(subset=['Gender','Pclass'],keep ='last')]

In [ ]:
# Create duplicate data
df_dup = pd.DataFrame({
    'id': [1, 2, 2, 3, 3, 3],
    'value': ['a', 'b', 'b', 'c', 'c', 'c']
})
print("Data with duplicates:\n", df_dup)

# Check duplicates
print("\nDuplicated rows:")
print(df_dup.duplicated())

# Count duplicates
print(f"\nNumber of duplicate rows: {df_dup.duplicated().sum()}")

# Drop duplicates (keep first by default)
df_no_dup = df_dup.drop_duplicates()
print("\nAfter drop_duplicates():\n", df_no_dup)

# Drop duplicates based on subset of columns
df_dup_subset = df_dup.drop_duplicates(subset=['value'])
print("\nDrop duplicates based on 'value' column:\n", df_dup_subset)

## 14. Pivot Tables and Cross Tabulation

In [ ]:
# Pivot table: survival rate by class and sex
pivot = pd.pivot_table(titanic, values='Survived', index='Pclass', columns='Sex', aggfunc='mean')
print("Pivot table (survival rate):")
print(pivot)

# Cross tabulation (frequency counts)
crosstab = pd.crosstab(titanic['Pclass'], titanic['Survived'], margins=True)
print("\nCross tabulation:")
print(crosstab)

# With normalization
crosstab_norm = pd.crosstab(titanic['Pclass'], titanic['Survived'], normalize='index')
print("\nNormalized by class:")
print(crosstab_norm)

## 15. Reading and Writing Data

In [ ]:
# Write to CSV
titanic_sample = titanic.head(100)
titanic_sample.to_csv('titanic_sample.csv', index=False)
print("Saved to CSV")

# Read from CSV
df_csv = pd.read_csv('titanic_sample.csv')
print("Read from CSV, shape:", df_csv.shape)

# Write to Excel (requires openpyxl)
# titanic_sample.to_excel('titanic_sample.xlsx', index=False)
# df_excel = pd.read_excel('titanic_sample.xlsx')

# Write to JSON
titanic_sample.to_json('titanic_sample.json', orient='records')
print("Saved to JSON")

# Write to Parquet (efficient binary format)
# titanic_sample.to_parquet('titanic_sample.parquet')
# df_parquet = pd.read_parquet('titanic_sample.parquet')

## 16. Basic Plotting with Pandas

In [ ]:
# Line plot
ts = pd.Series(np.random.randn(100), index=pd.date_range('2024-01-01', periods=100))
ts.plot(title='Random Time Series', figsize=(10, 4))
plt.show()

# Bar plot
titanic['Pclass'].value_counts().sort_index().plot(kind='bar', title='Passenger Count by Class', color='skyblue')
plt.ylabel('Count')
plt.show()

# Histogram
titanic['Age'].dropna().plot(kind='hist', bins=30, title='Age Distribution', alpha=0.7)
plt.xlabel('Age')
plt.show()

# Scatter plot
titanic.plot.scatter(x='Age', y='Fare', alpha=0.5, title='Age vs Fare')
plt.show()

## 17. Advanced Tips and Tricks

- **Memory optimization**: Use `pd.read_csv(..., dtype={'col': 'category'})` for low-cardinality columns.
- **Chunking large files**: `pd.read_csv('large.csv', chunksize=10000)`.
- **Efficient conditionals**: `np.where` for vectorized if-else.
- **String methods**: `df['col'].str.contains()`, `str.startswith()`, `str.extract()`.
- **Working with large data**: Use `pd.read_csv(..., usecols=[...])` to load only needed columns.

In [ ]:
titanic['Gender'].str.title()

In [ ]:
titanic.columns

In [ ]:
titanic.insert(2,'Title1',titanic['Name'].str.extract('([A-Za-z]+)\.'))

In [ ]:
titanic['Name']  = titanic['Name'].str.replace('Miss','Miss.')

In [ ]:
titanic

In [ ]:
# Using np.where for new column
titanic['Child'] = np.where(titanic['Age'] < 18, 1, 0)
print("Children count:", titanic['Child'].sum())

# String methods
titanic['Title'] = titanic['Name'].str.extract('([A-Za-z]+)\.')
print("\nTitle counts:")
print(titanic['Title'].value_counts())

# Chaining operations
result = (titanic
          .query('Age > 18')
          .groupby('Sex')['Fare']
          .mean())
print("\nAverage fare for adults by sex:")
print(result)

## Summary

Congratulations! You've covered:
- **Series and DataFrame** creation and attributes
- **Indexing** with `loc`, `iloc`, boolean filtering
- **Handling missing data** (detect, drop, fill)
- **Data type conversion** (to numeric, datetime, category)
- **Aggregations and descriptive statistics**
- **GroupBy** for split-apply-combine
- **Merging and concatenating** DataFrames (all join types)
- **Apply family** (`map`, `apply`, `applymap`)
- **Datetime** manipulation and resampling
- **Duplicates** handling
- **Pivot tables and crosstab**
- **Reading/writing** common file formats
- **Basic plotting**
- **Advanced tips** for efficiency

Pandas is an essential tool for any data professional. Practice with real datasets to solidify these concepts.